### ISSUE TITLE
Broken links in ecosystem section

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#1000]
To reproduce click on nav item `Stacks token` then click on `Contributing`. Expected: a link. Actual: nothing happens. 

Inspected and there is simply no `<a>` while this page is loaded. It works properly while other pages are loaded so I assume a bug vs. a content change. 

![Screen Shot 2020-12-31 at 9 47 41 AM](https://user-images.githubusercontent.com/767828/103414882-bff4f980-4b4d-11eb-868d-c0c5b5ebd82e.png)

**Comment by agraebe** [comment]
This is interesting. I just tried for myself and it worked. @jeffdomke do you see any errors in the console? Is anything indicating it's loading after you click?


@aulneau is this one of these content blocking issue we saw in the past?

**Comment by aulneau** [comment]
I can reproduce this, i'll assign myself and fix it :)

**Comment by agraebe** [comment]
@aulneau was this fixed?

**Comment by agraebe** [comment]
@aulneau did you have a chance to fix this?
