### ISSUE TITLE
Display bug with [@page-reference ]

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#1026]
[![Screenshot_2021-01-11_19-45-19.png](https://mrkr.io/s/5ffcaacf90fb0c69ac83518f/2)](https://mrkr.io/s/5ffcaacf90fb0c69ac83518f/0)

I keep seeing these. The markdown looks OK so inclined to think it is rendering funky for some reason. 

---

**Source URL:** [https://blockstack-docs-git-mainnet-docs.blockstack.vercel.app/start-mining/mainnet](https://blockstack-docs-git-mainnet-docs.blockstack.vercel.app/start-mining/mainnet)

<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.88</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>2007 x 1226</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by aulneau** [comment]
fixed in master
https://docs.blockstack.org/start-mining/mainnet
commit here: https://github.com/blockstack/docs/commit/529df3502f11d6f882d976d982215276ccd5062c#diff-5da5b88049a8268a82ad826128717667c81ac6e4c8fcee5218a17d559dfc1099R23

closing :)

**Comment by jeffdomke** [comment]
Such fast service here.
