### ISSUE TITLE
Add PoX requirements to the docs

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#1027]
We should have a section that explains the checks pox is doing in each cycle to determine if pox will be active

**Comment by pgray-hiro** [comment]
Using this issue to track additional PoX content that is needed per the RSK learnings document:

- Who are Stackers and what is their relationship to miners
- Role of Stackers in the PoX consensus mechanism
- How does the PoX protocol mitigate the perceived security risk of miners also stacking
- How does PoX contribute to the larger Bitcoin community
- Eventual sunsetting of PoX and fallback to PoB
