### ISSUE TITLE
Facing problems with Public registry app tutorial

### ISSUE THREAD

**Issue by serv** [blockstack/docs#1046]
I am currently going through https://docs.blockstack.org/build-apps/tutorials/public-registry and I am facing several problems.

# Problem 1: Lacking instruction to install dependencies for `Registering a public URL`

I needed to install

- @stacks/connect-react
- @stacks/transactions
- lodash-es

# Problem 2: `Unhandled Rejection (Error): This must be used within the ConnectProvider component.`

Once I install the dependencies above, I am at least able to start the app.
When you are signed out, you don't see this problem. Once you sign in, you see this error.

`Unhandled Rejection (Error): This must be used within the ConnectProvider component.`

![reacterr](https://user-images.githubusercontent.com/103456/104831410-8e627a80-583d-11eb-9f97-1ea56b3d2911.png)

I don't have enough knowledge to solve this problem. Can someone knowledgeable fix the doc to fix the above 2 problems?
Thanks.

**Comment by agraebe** [comment]
@hstove or @markmhx - could you chime whenever you have a chance? 🙏🏼

**Comment by agraebe** [comment]
@markmhx would you be able to review as part of your planning?

**Comment by markmhx** [comment]
@agraebe I've put this into the UserX icebox in case we can prioritize contributions here soon. However, given that the platform team will own Stacks.js (including the connect package) going forward, perhaps it'd be best to incorporate into that team's planning instead?

I realize ownership here has been blurry in the past, so perhaps we should sync generally about Stacks.js and related documentation contributions given our new team structuring

@friedger Have you seen this error in the past when writing this tutorial by chance?

**Comment by dcsan** [comment]
I'm going through the tutorial and immediately hit this problem. 
I've been trying all different directions to get a basic functional stacks web app, with each repo I try there's some blocker.

@serv did you ever solve this error - from JANUARY?

I notice theres another breadcrumb a bit later in the tutorial

```
// src/components/Sharer.jsx
<PublicUrlRegistrar userSession={userSession} />
```

I'm guessing this might be the branch and code for the tutorial? 
https://github.com/friedger/blockstack-todos/tree/tut/public-registry

**Comment by dcsan** [comment]
So that branch, i'm not sure if it's the whole thing, it just looks like the todo app, but at least it runs

I don't see anything like a provider or anything that looks like it might be the `ConnectProvider Component` so i guess the error message is misleading.

The parent component has this:

```
export const Sharer = ({ togglePublic, isPublic }) => {
  const { authOptions } = useConnect();
  const { userSession } = authOptions;

...
                  <PublicUrlRegistrar userSession={userSession} />

```

which has the problem fn in it:

```
export const PublicUrlRegistrar = ({ userSession }) => {
  const { doContractCall } = useConnect();
```

this is normally where it blows up. So maybe if we put two nested `useConnect()` calls it might be worth trying?
That doesn't seem to make any sense, if it breaks further down it should also break in the app root.

Guess I'll keep looking for clues...

**Comment by dcsan** [comment]
This tut hasn't been touched for about two years, so I'm guessing all the libraries are out of date.

So given these tutorials are out of date and may take some time to get working again,  can any dear readers suggest a modern stacks tutorial that has been used recently and shows how to call a signed contract method?

The nft-nyc thing looked interesting but that's also [not functional](https://github.com/hirosystems/nft-nyc-exclusive-app/issues/4) at least in the current repo state.

**Comment by dcsan** [comment]
OK checking some of the source I assume this is the issue:

https://github.com/hirosystems/connect/blob/main/packages/connect-react/src/react/hooks/use-app-details.tsx

```
  const { authOptions } = useContext(ConnectContext);
  if (!authOptions.appDetails) {
    throw new Error('This must be used within the ConnectProvider component.');
  }
```

so it is a looking for a context to use...  that's a bit different from the current tutorial, so maybe that was a change in the hiro `connect-react`

**Comment by dcsan** [comment]
OK I think i have the minor change to make it work:
in the parent component wrap it like this

```
import { Connect } from "@stacks/connect-react";

export default function HomePage() {
  const authOptions = {
    appDetails: {
      name: "SOMETHING",
      icon: window.location.origin + "/assets/logo.png",
    }
  }

  return (
    <Box className="home-page-container">
      <Connect authOptions={authOptions} >
        <AuthButton />
      </Connect>
    </Box>
  );
}
```

and then in the `ChildComponent` you can continue as usual...

```
export const AuthButton = () => {
    const { authOptions } = useConnect();

    function doLogin() {
        showConnect({
            appDetails: {
                name: 'YOURAPP',
                icon: window.location.origin + '/assets/astro/zodiac-200.png',
            },
            redirectTo: '/',
            onFinish: (result: any) => {
                // window.location.reload();
            },
            onCancel: () => {
                console.log('cancelled')
            },
            userSession: userSession,
        });
    }

    return (
            <Button onClick={doLogin} size='lg' p={10}> Sign In </Button>
    )

}

```

**Comment by markmhx** [comment]
@dcsan Thanks for investigating this issue. Might you want to help resolve this on the `connect-react` repository level by submitting a PR that patches it for others?

cc @friedger

**Comment by dcsan** [comment]
its mainly a problem with the demo app, not the repo. the plugins have all moved ahead and aren't backward compatible.

for this particular app i think it's a branch inside the TODO app, so it will end up being a hairball

in theory I could make a new repo just of the registry app, use the latest version of the hiro plugins, and check it works?

but i'm more tempted to look into micro-stacks and other libs right now and create a better reference app with NFT mint features etc.

**Comment by markmhx** [comment]
@agraebe mind providing some guidance here on the next steps from your perspective? This is ultimately a question of how this example app should support Hiro docs and the developer journey going forward.

**Comment by agraebe** [comment]
_Note: Now that the Hiro and Stacks docs are split, this particular issue should be on the [Hiro docs repo](https://github.com/hirosystems/docs/). The tutorial is now available here https://docs.hiro.so/example-apps/public-registry. A new issue was created: https://github.com/hirosystems/docs/issues/50_

> in theory I could make a new repo just for the registry app, use the latest version of the hiro plugins, and check it works?

This would be my suggestion, too. I think the sample code (for both the todo and the registry app) wasn't touched for a long time and we'd be better off with a clean slate. @dcsan if you would be open to sharing a working sample, I would love to use your code in the tutorial!

**Comment by dcsan** [comment]
@agraebe i mostly just used the references to build my own app, so don't have a "working version" of this app.
that said the above is the main change that's needed, just make sure to provide a connect wrapper

```ts
      <Connect authOptions={authOptions} >
        <AuthButton />
      </Connect>
```

**Comment by agraebe** [comment]
great, thanks for the note! once we get to revisit the sample code, I'll make sure to update that part.

**Comment by javalight** [comment]
I've run into the exact same problem when working with the tutorials. Any time the tutorials are going to be updated?

Also the billboard app tutorial has an issue, I suspect its that the app is not compatible with the newer version of clarinet.

Running **clarinet integrate**  or **clarinet check**

```
error: Failed to lex input remainder: '
;; billboard contract
...
```
Error in the billboard.clar file.

**Comment by friedger** [comment]
The tutorials are now maintained at https://github.com/hirosystems/docs/tree/main/docs @javalight
