### ISSUE TITLE
Hello-world-tutorial not working. It is pointing to mainnet : how to change to testnet? ref https://docs.blockstack.org/write-smart-contracts/hello-world-tutorial

### ISSUE THREAD

**Issue by procloudadmin** [blockstack/docs#1052]
Hello 

The tutorial at https://docs.blockstack.org/write-smart-contracts/hello-world-tutorial uses a Gitpod playground that comes pre-installed with the Stacks CLI.

I am trying to follow the clarity-hello-world and at step 5 I am unable to get some testing tokens, obtaining the error :

 "error" : "Error: Response 400: Bad Request fetching http://stacks-node-follower-0.stacks-node-follower.prod-stacks.svc.cluster.local:20443/v2/transactions - {"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid tx e0c4a1e77957ec4669933685ccb2617c3b46e0111a937bd992c0b0a954bec0e7: invalid chain ID 2147483648 (expected 1)"},"txid":"e0c4a1e77957ec4669933685ccb2617c3b46e0111a937bd992c0b0a954bec0e7"}",
   "errorTag" : "70883e1a-f42d-41e1-83ea-91d76b2c6423",
   "stack" : "Error: Response 400: Bad Request fetching http://stacks-node-follower-0.stacks-node-follower.prod-stacks.svc.cluster.local:20443/v2/transactions - {"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid tx e0c4a1e77957ec4669933685ccb2617c3b46e0111a937bd992c0b0a954bec0e7: invalid chain ID 2147483648 (expected 1)"},"txid":"e0c4a1e77957ec4669933685ccb2617c3b46e0111a937bd992c0b0a954bec0e7"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)\n    at async /app/lib/api/routes/faucets.js:186:37\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)"

In was tol the error is because you are using the mainnet (Chain ID 1) endpoint instead of testnet (chain ID 2147483648) , I was just following a step by step and no instructions to change that parameter

where can I fix this chain ID ?     we need to fix the tutorial as well

Thanks

**Comment by agraebe** [comment]
we rolled out an update today to fix the docs. Step 5 is now pointing to the testnet node URL. It used to point to the mainnet URL. Could you try again?

```shell
# replace <stx_address> with `address` property from your keychain
curl -XPOST "https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx?address=<stx_address>" | json_pp
```

**Comment by procloudadmin** [comment]
Hello

I retried and it works ,
I obtained

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100   463  100   463    0     0    524      0 --:--:-- --:--:-- --:--:--
524
{
   "success" : true,
   "txId" :
"0x3b1082497ebe0592e1ec1a8ad9da239eaeaa8283de1c790c65f18157f1dc8ded",
   "txRaw" :
"80800000000400164247d6f2b425ac5771423ae6c80c754f7172b0000000000000003600000000000000b4000163e3171cb75ff27e69338d543588a31f17934032e65aa7769135984ae8ead37552613dba881e1c1ad6ef15a376c641c0f7a6d43027e1bbe378ce593715ce0f6203020000000000051a1ddc6a60654dc53063df6ca13c2e4aa67883c902000000001dcd650046617563657400000000000000000000000000000000000000000000000000000000"
}


thanks

Fernando Cabal

**Comment by agraebe** [comment]
great
