### ISSUE TITLE
Add account balances, common error to local dev tutorial

### ISSUE THREAD

**Issue by friedger** [blockstack/docs#1065]
There are common error and tasks that contract developers want to do:
- how to handle docker issues
- how to setup account balances, list private keys
- how to deploy a contract
- how to switch between local dev and testnet/mainnet
- how to setup the explorer
- how to enable/disable import of stacks 1.0 chainstate
- clarity when you need the miner, and when you don't.

**Comment by friedger** [comment]
example: 
```
ERROR: for mocknet_bootstrap  Cannot create container for service bootstrap: Conflict. The container name "/mocknet_bootstrap" is already in use by container "a921cc887695c08bda8c32e0ed7b6ba3602078208d01ce1d2b83301bc804f961". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by agraebe** [comment]
mind helping out with a PR?

**Comment by agraebe** [comment]
this seems not as relevant anymore with the existence of Clarinet. Closing for now - please reopen if you think otherwise 🙏🏼
