### ISSUE TITLE
Update FAQ grid links

### ISSUE THREAD

**Issue by cuevasm** [blockstack/docs#1074]
Heyo, in the process of making sure information is up to speed and trying to reduce some surface area for maintenance. Also eliminating our reliance on Zendesk. More info here if desired: https://paper.dropbox.com/doc/FAQ-Adjustments--BEzQrtcRcVoEDRnhDL1S3nQbAg-jliXyUknD93Q73G9IiNaX, but I have pulled out concrete changes and mapped them below.

The following changes are good with leads/Ryan. 

![Add a heading (8)](https://user-images.githubusercontent.com/6131188/107454222-45a89380-6b55-11eb-9f32-d82396e42fad.png)

Corresponding updates:
1. 
Title: General Information
Description: Learn more about the user-owned internet on Bitcoin and the Stacks ecosystem
Link: https://stacks.co 

2. 
Title: Stacks Token
Description: Stacks fuel apps and smart contracts on Bitcoin
Link: https://stackstoken.com/faq (this page will resolve to a fresh page of FAQs soon, but switch can be made ahead of that)

3.
Title: Stacks Network
Description: Learn more about the network behind the user-owned internet on Bitcoin 
Link: https://docs.blockstack.org/understand-stacks/overview

4.
Title: Stacks Wallet
Description: Download and find resources about the Stacks Wallet by Hiro
Link: https://www.hiro.so/wallet

5.
Title: Apps and Smart Contracts
Description: Developer, get started building
https://www.stacks.co/developers

Once that's done, maybe move the tiles around so that the order is 1, 5, 3, 2, 4

**Comment by agraebe** [comment]
what's the urgency on this? I just checked and this change requires more than just updating markdown/content. This touches the integration with zendesk it seems, cc @aulneau

**Comment by cuevasm** [comment]
We should not need to touch Zendesk. I purposely avoid using any content from there going forward. These panels are now linking to outside resources vs. internal pages populating from ZenDesk. The FAQs that are being pulled in should just go away, eliminating any reliance on ZD

**Comment by agraebe** [comment]
Right, I understand. The implementation in the docs is integrated with Zendesk and would need to be changed to just show static links. We'd probably have to rely on @aulneau to help

**Comment by aulneau** [comment]
Yes that is correct -- there is some dev work here. I can work on this next week if that works for the timing.

**Comment by cuevasm** [comment]
I see! Works for me, thank you both!

**Comment by cuevasm** [comment]
Checking if it'll still be possible to get to this during the week - no huge issue if not, just trying to plan, thank you!

**Comment by cuevasm** [comment]
Bump, it's Thursday of my last week and hoping to get ZD totally shut down. Will we be able to knock these tiles out in the next couple days?

**Comment by agraebe** [comment]
I can't help here, unfortunately. we need @aulneau to help - not sure if he can prioritize in the next few days. 

@aulneau could you chime in? 🙏🏼

**Comment by cuevasm** [comment]
Hey @aulneau - running low on days I have Ryan around to help me finish this up, can we re-link those tiles before end of week?

**Comment by aulneau** [comment]
@cuevasm Sorry more pressing things have taken my time. I don't think I can get to this this week. CC @andresgalante for visibility

**Comment by cuevasm** [comment]
Alright, it's been a couple weeks now and this seems like something maybe we should open up such that more folks can help make these changes so we can move more quickly on public-facing resources. 

Not trying to harp, but this is some light text updates and changing out hyperlinks and should immediately clear up a ton of confusion and support requests.

**Comment by andresgalante** [comment]
Hi @cuevasm I understand that this is an easy fix, unfortunately, this is not the only fix he has to deal with, and with the restructuring of the Engineering team, he is being pushed in all directions.

Since this issue was open he has release major performance improvements to the Explorer, helped release delegation, performed a complete PR review of the alfa branch of the web wallet, and lead a fix to a security vulnerability (just to mention a few).

We have an understaffed team and at the moment Docs is not on Thomas' hands anymore since he moved to UX.

Having said that I'll make to get this fix out early next week and @alexkeating let's sync on how we can handle requests to Docs moving forward so we don't end up with simple fixes open for 2 weeks.

**Comment by agraebe** [comment]
let me how on it

**Comment by cuevasm** [comment]
To be clear, I'm not questioning that a bunch of important work was done and I very much understand how understaffed things are. I think vs. just letting that keep being the case, I am calling it out so hopefully, we can address on a resource level, because as much as we're pulled in lots of directions, I can't be convinced something like this should take over 2 weeks. I say all this with love and appreciation and in hopes we can get you more help.

I am also not the one that looped in Thomas, I just made the ticket, I always leave it to ya'll how you want to staff

**Comment by andresgalante** [comment]
100% agreed. This should not have taken 2 weeks. Lesson learned and let's improve our process for next time
