### ISSUE TITLE
New stacks-local-dev image env vars

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#1083]
The latest API images included in `stacks-local-dev` require new env vars:

```
API_STACKS_CHAIN_ID=0x00000001
API_V2_POX_MIN_AMOUNT_USTX=70000000260
```

The docs should reflect that. Specifically, this page: https://docs.blockstack.org/understand-stacks/local-development

cc @wileyj

**Comment by wileyj** [comment]
I don't think there's an update to be required here; we haven't documented **every* env var being set, and we'd really have to ask @zone117x for an explanation of what these are for, and what changing them will do (if they can be changed outside of the network being run).

**Comment by wileyj** [comment]
right now, they're set for the different networks in the different network branches

**Comment by agraebe** [comment]
okay, sounds like this can be closed. thanks for checking!
