### ISSUE TITLE
Tutorial/guide(s) on how to program with Bitcoin state

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs#1088]
This is one of Stacks and Clarity's value props but I don't see any resources on how to actually write smart contracts that use Bitcoin state. Would this be worthy of its own tutorial or guide?

**Comment by agraebe** [comment]
yes, this is now part of the #749 issue. The goal is to come up with a new tutorial that shows the relationship to the bitcoin networked during onboarding.

As far as I understand, the bitcoin state programming would be possible with stacks 2.1. @lgalabru and @kantai to confirm
