### ISSUE TITLE
Replace docs menu

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs#1090]
![image](https://user-images.githubusercontent.com/25477905/108986037-00767c80-7692-11eb-90de-53b6d737196a.png)

The current menu is the same as the old blockstack.org menu. We should replace it.

**Comment by agraebe** [comment]
can you also make the code changes or do you need support from myself or @aulneau ?

**Comment by pgray-hiro** [comment]
Hey @jasperjansz can you clarify what the change you're looking for here is? Is it the navigation on the top right?
