### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by aulneau** [blockstack/docs#1105]
The favicon is out of date and should be updated to the STX nexus icon.

**Comment by eugeniadigon** [comment]
[favicon_io (1).zip](https://github.com/blockstack/docs/files/6241610/favicon_io.1.zip)

**Comment by kyranjamie** [comment]
@eugeniadigon There's currently a light & dark mode favicon. Can you provide the assets for both modes in  .svg?

**Comment by eugeniadigon** [comment]
[favicon.zip](https://github.com/blockstack/docs/files/6341638/favicon.zip)
Sure here they are @kyranjamie
