### ISSUE TITLE
Improve documentation for passing params to contract calls

### ISSUE THREAD

**Issue by hstove** [blockstack/docs#1108]
The CLI currently supports passing params to a contract call (for some types, not all). You first enter the CLI commands for `contract_call`. Then, the CLI will fetch the contract interface and allow you to type in the params.

This behavior is pretty non-obvious. We should at least add documentation, or an example, to how this works on the CLI reference page.

**Comment by friedger** [comment]
The CLI does not allow to specify post conditions. This should also be documented.
