### ISSUE TITLE
Add documentation for username registration via BNS for Stacks 2.0

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#1111]
It doesn't appear we have any good place to send developers wondering how to integrate BNS into their apps or otherwise execute BNS-related contract functions separately on Stacks 2.0 (e.g. instructions on how to register usernames for users or transfer usernames between users).

**Comment by pxydn** [comment]
we should prioritize:
- teaching users how to register a username on .id
- a simplified description of how BNS works
- registering their own namespaces

happy to help with this. 

potentially when we launch DDNS, we can add a tutorial to this section for how users can get started with that, and how developers can register names on it.

**Comment by 314159265359879** [comment]
I would like to know how to use the explorer sandbox for registering namespaces and BNS names as this will work regardless of available apps. And it is convenient to have a workflow that works for both testnet and mainnet.

**Comment by 314159265359879** [comment]
![image](https://tweakers.net/i/n_gPJWC8xi-cQP5wdq7AUw9bH8M=/full-fit-in/4920x3264/filters:max_bytes(3145728):no_upscale():strip_icc():fill(white):strip_exif()/f/image/jFNBOFEmqNFMSBewmoOiLrDT.jpg?f=user_large)

Here are some issues I am running into when trying to preregister a namespace through the explorer sandbox. It has a buffer of 20 for the _hashed-salted-namespace_ whereas all the 160 bit hashing algorithms I know of (RIPE-MD160, SHA0/SHA1 and Tiger-160) produce strings of 40 characters.
- What hashing should be used here?
- Wouldn't it make more sense for this field (hashed-salted-namespace) to accept 40 chars in HEX? instead of 20 chars in ASCII?
- Now the transaction fails with BadFunctionArgument because it does not accept the strange ASCII characters (provided screenshot).

**Comment by pxydn** [comment]
@314159265359879 
- hash160 uses RIPEMD160(SHA256(x))
- yes, i think it would make more sense for 40 chars? not too sure on this
- read no 1

"hash160" is using the clarity impl. check [here](https://docs.blockstack.org/references/language-functions#hash160).

i'm attempting to register `.ddns` on testnet. will update on how it goes. 
**txid:** `0xd2a2150e59d1771df9bdb9aeb090b83d0eac7ddc560dd09cf910f82c18bb87f6`

**Comment by friedger** [comment]
Some content:
Pool registry is using clarity do pre order and registration in on tx https://gitlab.com/riot.ai/clarity-pool-registry
```
(define-private (register-name (name (tuple (namespace (buff 20)) (name (buff 48)))) (user principal))
   (match (print (contract-call? 'ST000000000000000000002AMW42H.bns name-preorder (hash160 (concat (concat (concat (get name name) 0x2e) (get namespace name)) 0x00)) (unwrap! (get-name-price name) (err ERR_NAME_PRICE))))
      result-preorder
         (match (print (contract-call? 'ST000000000000000000002AMW42H.bns name-register  (get namespace name) (get name name) 0x00 0x00 ))
            result-register (ok true)
            error (err (to-uint error)))
      error (err (to-uint error))))
```      

Transfer BNS 1.0 name from address without stx to new address:
```
async function transfer(namespace: string, name: string, newOwner: string) {
  const seedPhrase = sk.phrase;
  const rootNode = await deriveRootKeychainFromMnemonic(seedPhrase);
  const child = rootNode
    .deriveHardened(888)
    .deriveHardened(0)
    .deriveHardened(1);
  const privateKey =
    (child.privateKey?.toString("hex") || "invalid key") + "01";
  let stxAddress = getAddressFromPrivateKey(
    privateKey,
    TransactionVersion.Testnet
  ); // !! deriving address using uncompressed key
  console.log("wrong address", stxAddress);
  const pubKey = createStacksPublicKey(child.publicKey.toString("hex"));
  stxAddress = publicKeyToAddress(AddressVersion.TestnetSingleSig, pubKey); // !! deriving address using compressed key
  console.log("correct address", stxAddress);
  try {
    // const poxInfo = await infoApi.getPoxInfo()
    // const [contractAddress] = poxInfo.contract_id.split(".");
    const contractAddress = "ST000000000000000000002AMW42H";

    console.log(privateKey);
    const tx = await makeContractCall({
      contractAddress,
      contractName: "bns",
      functionName: "name-transfer",
      functionArgs: [
        bufferCVFromString(namespace),
        bufferCVFromString(name),
        standardPrincipalCV(newOwner),
        noneCV(),
      ],
      postConditions: [
        makeStandardNonFungiblePostCondition(
          stxAddress,
          NonFungibleConditionCode.DoesNotOwn,
          createAssetInfo("ST000000000000000000002AMW42H", "bns", "names"),
          tupleCV({
            name: bufferCVFromString(name),
            namespace: bufferCVFromString(namespace),
          })
        ),
      ],
      network,
      senderKey: privateKey,
      sponsored: true,
    });

    const sponsoredTx = await sponsorTransaction({
      transaction: tx,
      sponsorPrivateKey: secretKey,
      network,
    });
    console.log(sponsoredTx);
    const result = await handleTransaction(sponsoredTx);
    console.log(result);
  } catch (e) {
    console.log(e);
  }
}
```
