### ISSUE TITLE
Diagram: Stacks and Bitcoin

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#1142]
A technical diagram showing the relationship between Stacks and Bitcoin would be great! This would illustrate content of a new docs page that will be added as part of the new NFT onboarding flow

**Comment by jasperjansz** [comment]
@agraebe does EOW work for you?

**Comment by jasperjansz** [comment]
@agraebe I have some prelimary drafts here: https://www.figma.com/file/7aM6jrgeSSfXYuwjUvRYHW/pox-diagram?node-id=0%3A1. I'm not sure what you're looking for — how detailed and what part of the Stacks <> Bitcoin connection. Can you share more, or link to a draft of the new docs page so I have more context?

**Comment by agraebe** [comment]
these look great! @jdbender66 will work on the content, so I'll let him chime in.

cc @pgray-hiro

**Comment by jdbender66** [comment]
@jasperjansz Yeah these are fantastic! Understandable and sorry for the misguidedness. It would certainly be harder to visualize the more hardcore technical aspects of PoX, but the three images you provided are great high-level accompaniments for the docs. I'm working through some copy for the docs and tutorial now, and might have some more context for you in the future. These are fine for now though, thank you.

**Comment by pgray-hiro** [comment]
This issue was closed by #1161 .
