### ISSUE TITLE
Production deployment guide for Stacks Blockchain API

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/docs#1162]
Most people who are running stacks nodes often end up wanting / needing to run API instances. If one were to try to find instructions on how to run an API instance in a production environment today, they would struggle to find meaningful information in our docs or in the API repo's README or anywhere else. We end up pointing people to https://github.com/blockstack/stacks-local-dev and do a lot of one-off hand-holding to just get the API up and running.

Instead, we should invest in a comprehensive production deployment guide that's based on best-practices informed by Hiro's experience running these services, and make it as easy to follow and as discoverable as possible.

cc/ @wileyj @CharlieC3 @zone117x @pgray-hiro

**Comment by wileyj** [comment]
related: https://github.com/hirosystems/devops/issues/708

**Comment by whoabuddy** [comment]
I am managing an API node and would be happy to write up some documentation on following those best practices once published! 👍

**Comment by wileyj** [comment]
> I am managing an API node and would be happy to write up some documentation on following those best practices once published! 👍

@whoabuddy would you mind telling me *how* you're running the service? are you compiling and running from source or using docker?

**Comment by wileyj** [comment]
First pass at a docker-focused guide: https://github.com/blockstack/stacks-blockchain-api/blob/feat/running-api-docs/running_an_api.md

**Comment by wileyj** [comment]
https://github.com/blockstack/stacks-blockchain-api/issues/499

**Comment by whoabuddy** [comment]
@wileyj sorry I didn't see this sooner! Feel free to ping me in Discord for a faster response as my GitHub is flooded with messages.

For our setup I gave in and used Docker, but would much prefer to build from source. Currently using Digital Ocean for hosting the server and Cloudflare for managing the DNS. I also have a shell script that spits out some stats to Discord on a 12hr interval using a modified version of stacks-dump.

We currently use it for querying wallet balances and stats needed for hodl score in Freehold, but with CityCoins having potential for a large amount of traffic, I'd like to beef it up and make it useful as an alternative to the Hiro API for the UI interactions.

I'd also like to explore load balancing and potential for running multiple instances if needed, and feel there is some shared knowledge we could definitely collaborate on.

I will make it a priority to review the docs above this week and let you know if I have any questions or updates!

**Comment by CharlieC3** [comment]
@zone117x I mentioned this to @whoabuddy in Discord, but I'll be writing a blog post on how we configure and manage our blue/green deployments for the API. Not sure how much sense it would make to have this in our official docs, since there's plenty of ways to achieve this, but exposing how we do it is good material for the blog.

**Comment by zone117x** [comment]
@CharlieC3 makes sense!
I think it might be useful to cover the API proxy env vars like "these can point to a load balanced cluster", but maybe that's already self evident.
