### ISSUE TITLE
Todos App tutorial fails to start due to dependency error

### ISSUE THREAD

**Issue by pgray-hiro** [blockstack/docs#1170]
When pulling the Todos App repo, if you perform `yarn && yarn run start`, the process will fail to start with the following error:

```
The react-scripts package provided by Create React App requires a dependency:

  "jest": "24.9.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of jest was detected higher up in the tree:

  /Users/patrick/src/todos/node_modules/jest (version: 25.5.4) 

Manually installing incompatible versions is known to cause hard-to-debug issues.
```

According to @aulneau, this is caused because `jest` is listed in the `dependencies` of the`@stacks/connect` package, rather than the `devDependencies`.  Resolve this dependency error.

**Comment by markmhx** [comment]
@aulneau did you mention wanting to take this one or might someone else on the team be best?

**Comment by pgray-hiro** [comment]
The dependencies are now fixed - we're just waiting on the package to be published and the dependency to updated in the todos tutorial itself.
