### ISSUE TITLE
Todos app identity not working as documented with Web Wallet

### ISSUE THREAD

**Issue by pgray-hiro** [blockstack/docs#1171]
The Todos App tutorial is centered around signing in using the old Blockstack ID system.  The app will allow you to sign in with the web wallet, but is broken when making your Todos public (doesn't generate the correct sharing URL).  There are other subtle breakages, as when the application won't show any user identity if the user doesn't own an ID in their wallet.

As I see it, there are two potential solutions to this issue:

- Rework the application to use something other than an identity to generate the sharing URL
- Create an easy way for users to create an identity and modify the copy of the documentation to include instructions on how to do that

The first would be the easier solution, but the second may be more pragmatic, as the creation of an easy identity purchase/generation application is likely necessary for other apps in the ecosystem.

**Comment by markmhx** [comment]
@wilsonbright I believe you mentioned awhile back having code you use to pull public Gaia data for a user without needing a username. Would you mind sharing it? If so, we could perhaps rework the app to generate sharing URLs with the user's identity address instead of username.

**Comment by ilayaperumalraja** [comment]
@markmhx , Form public URL with out username,

1. Get the gaia hub address of user from userSession object.
	let gaiaHubAddress = userSession.loadUserData().gaiaHubConfig.address;
	
2. Put file with unique name to gaia and it should be decrypted.
	userSession.putFile("uniqueName", "content", {encrypt: false});

3. Form gaia url and make a http call to get a file directly from gaia by (gaiaHubAddress + uniqueName).
	let directFileLoaction = "https://gaia.blockstack.org/hub/" + gaiaHubAddress + "/" + "uniqueName";
	Make a http call to "directFileLoaction" url. You will receive a file content.
	
4. Form publicly shareable url
	In previous setup, we need two dynamic values to form gaia URL "gaiaHubAddress and uniqueName". These values need to be part of publicly shareable URL.
	https://yourdomain/gaiaHubAddress/uniqueName

**Comment by markmhx** [comment]
Thanks @ilayaperumalraja! Note that @aulneau also has an app in the works that will help with the alternative path of having them register a username elsewhere then use the todos app. So with this code guidance and that app available soon, both options seem viable.

**Comment by markmhx** [comment]
Note that the related Stacks.js fix for querying public user data without a username is filed here: https://github.com/blockstack/stacks.js/issues/802

**Comment by markmhx** [comment]
@pgray-hiro the team discussed this issue and we're thinking it'd be best to link to [the .BTC app](http://btc.us/) for now from the documentation, indicating that users should buy a username from there before proceeding with the todos app.

We're also discussing the re-enabling of free username registration in the web wallet for Q3 but it's not yet clear if we'll prioritize it. And it seems best to unblock the docs with a solution for now, even if we eventually get that enhancement in place.

How's that sound?
