### ISSUE TITLE
Create easy mode for running a mainnet node

### ISSUE THREAD

**Issue by pgray-hiro** [blockstack/docs#1188]
Similar to the new workflow for running a Stacks API node, we should create an "easy mode" for running a mainnet/testnet node.

**Comment by wileyj** [comment]
in progress, i reckon this should be PR'ed to the `stacks-blockchain` repo for the markdown correct?

**Comment by pgray-hiro** [comment]
If you want to land markdown there, that's fine. If you wanted to just get me a Dropbox doc and I can adapt it for the Stacks docs, that works too. Ideally we don't need to maintain this information in multiple places, although we're already doing that for the API node doc.

**Comment by wileyj** [comment]
a fair point - would you prefer we only source this info from the main docs site? i'm ok with that - it would reduce the need to maintain multiple copies which can be a hassle.

**Comment by wileyj** [comment]
my preference will always be to create the text in markdown, but we don't need to PR it

**Comment by pgray-hiro** [comment]
Yea, my strong preference would be the docs site being the single source of truth here. If you want to create the markdown in a branch in the docs repo that would be awesome. I think it should live in `src/pages/understand-stacks/running-mainnet-node.md` - feel free to replace all the content that is already there as this Dockerized approach should be our "official" way of running one.

**Comment by friedger** [comment]
Fixed by #1245
