### ISSUE TITLE
Standardize how we display terminal/bash code blocks

### ISSUE THREAD

**Issue by wileyj** [blockstack/docs#1190]
We have prior art where we've typically used a code block like this to show terminal or bash commands:
```bash
$ echo "test string"
```

However, `Akirtovskis` mentioned in https://github.com/blockstack/stacks-local-dev/pull/39 that it would make things easier to remove the `$` from terminal/bash, like this:
```bash
echo "test string"
```

Personally, I agree with this approach - the only reason I had added the `$` is because of prior docs/readme's that we've published where the `$` exists. 

To keep this issue easily scoped, we should go through existing docs  here and remove the `$` or any other shell/terminal identifier ( `%` is another example). 
Later, it would be nice to work on a style-guide that we use here with the goal of standardizing how we create docs with the goal of making them easy and accessible. ( @pgray-hiro )

**Comment by Akirtovskis** [comment]
Happy to jump in and help with PRs that remove `$` and `%` in docs if some sort of list or scope of repositories is provided.

**Comment by pgray-hiro** [comment]
@Akirtovskis I would certainly love the assistance - I want to just put it to our dev team to make sure this is how we want to standardize, once we've sorted that out I can provide a resource list

**Comment by pgray-hiro** [comment]
@Akirtovskis After internal discussion and discussion with the community, we've settled on not including the `$` or `%` terminal prompt in any docs or READMEs. There is one exception to this rule, if the code block is showing the command and the example output of the command for example:

```sh
$ stx balance SP2JM9EMVHHRHWHW82CD9XQMTYTM8BG2RWG58WQVB
{
  "balance": "18588980982",
  "locked": "0",
  "unlock_height": 0,
  "nonce": 1609
}
```

In the above case it would be acceptable to leave as is, or as a best practice it would be preferred to split the example command and the output with some expository text between them.

As far as doc updates go, this repo would be the primary target, but we would appreciate additional PRs on READMEs in any repo in the `blockstack` organization. Let me know if this is something you can take on.

**Comment by Akirtovskis** [comment]
@pgray-hiro I am definitely up for doing this.

Just to clarify: for commands that have an output in the same text block, is it fine to do it the way I did in this PR?

https://github.com/blockstack/stacks-local-dev/pull/39

**Comment by Akirtovskis** [comment]
Creating a list of repos I have gone through here and created PRs: 

- [ ] https://github.com/blockstack/stacks-blockchain 
PR https://github.com/blockstack/stacks-blockchain/pull/2700 

- [ ] https://github.com/blockstack/stacks-local-dev
PR https://github.com/blockstack/stacks-local-dev/pull/44

- [ ] https://github.com/blockstack/subdomain-registrar 
PR https://github.com/blockstack/subdomain-registrar/pull/62
