### ISSUE TITLE
duplicated 'Proof of Transfer' on side nav

### ISSUE THREAD

**Issue by d1gitalflow** [blockstack/docs#1271]
![34334cxd](https://user-images.githubusercontent.com/26913156/136240663-a35a52d0-c671-4ba1-b2e0-097ce619999d.PNG)

Lets see if I can figure out the routing code to fix this duplicated

**Comment by d1gitalflow** [comment]
Made a PR, thanks :)

**Comment by friedger** [comment]
Fixed by #1272
