### ISSUE TITLE
Clarity overview page crashes on chrome

### ISSUE THREAD

**Issue by MarkAdell** [blockstack/docs#1278]
Whenever I open Clarity overview page on chrome it crashes and I'm unable to navigate to any other page

https://docs.stacks.co/write-smart-contracts/overview

**Comment by jhammond2012** [comment]
@MarkAdell are you still experiencing this issue? I am trying to replicate but I am not able to.

**Comment by jhammond2012** [comment]
Hi @MarkAdell I am going to go ahead and close this issue. If you are able to replicate this, please feel free to re-open the issue. Thanks!
