### ISSUE TITLE
Internationalization and Bahasa Indonesia Translation flag

### ISSUE THREAD

**Issue by empeje** [blockstack/docs#1284]
I think it is important to have Markdown i18n translation framework in place so people can start translating. Our team in @Stacks-Indonesia are willing to help with the translation for Bahasa Indonesia.

**Comment by jhammond2012** [comment]
Hi @empeje we actually just added this. We are integrating with a visual platform so community members can easily contribute. Please reach out to me on discord so I can help onboard you guys for translation efforts.

My username: 2n10se#5020

**Comment by jhammond2012** [comment]
Closing this issue. @empeje and I connected on Discord and he is being brought in for translation collaboration.
