### ISSUE TITLE
Improve explanation about running a private hub with a whitelist

### ISSUE THREAD

**Issue by hstove** [blockstack/docs#198]
When running a private Gaia hub, you only want you or authorized users to use it. This is made possible by adding a "whitelist" array to your Gaia `config.json` file.

~~~json
{
  "whitelist": [
    "my-id-here"
  ]
}
~~~

You can find your address in the Blockstack Browser. Go to the 'IDs' section, and we display it for you under your picture:

![identity](https://cl.ly/2b74debfa627/Image%202019-04-04%20at%206.44.28%20PM.png)

Copy the part after `ID-`, and that's what you want to put in your `whitelist` configuration. For me, that is `125s2W1ijbGgA7D3zviJiFTTErnWGRV67g`. After restarting your Gaia hub, it will only allow writes from that address.

We also have "association tokens", which are explained pretty well in the [gaia README](https://github.com/blockstack/gaia#association-tokens). Once we merge in [this PR for the Browser](https://github.com/blockstack/blockstack-browser/pull/1833), all authentications through the browser will generate an association token, which basically is a signed token that says "I am vouching that this different address is associated with my main address", so if the main address is whitelisted, then the other address will be allowed to write. This is needed because each individual app has a different Gaia address/bucket per user. Blockstack.js is already set up to use association tokens if they're made available from the Browser.

**Comment by zone117x** [comment]
Here's a WIP config-schema.json being generated from the actual source type definitions and default values: https://github.com/blockstack/gaia/blob/feature/config-type-DRY/hub/config-schema.json

Hope it helps with this doc effort

**Comment by moxiegirl** [comment]
@hstove do we have an example of "what the association token looks like in the header" --- I assume this is the auth header --- in the local storage --- I could look at that with the Dev Tools in my browser right?

**Comment by hstove** [comment]
With the new browser PR, the `authResponse` includes an `associationToken` property. When blockstack.js logs you in, it saves the association token in `localStorage`. Then, when you make a request to store data in Gaia, blockstack.js includes the association token in the authorization header. This is harder to inspect, but you can do it by decoding the whole auth token that is passed to Gaia.
