### ISSUE TITLE
Mismatch between code and docs on wire format token transfer endianness

### ISSUE THREAD

**Issue by alexmavr** [blockstack/docs#425]
In https://github.com/blockstack/docs.blockstack/blob/5868a3ff5799e5455552ba9c915ae077f218e5e7/_core/wire-format.md it is explicitly mentioned in the `TOKEN_TRANSFER` operation that: 

```
The amount field is an 8-byte litte-endian number that encodes the number of micro-Stacks.
```

However, looking at the client implementation in blockstack.js, we can see that a big-endian format is used, and the corresponding comment refers to `amount (BE)`:
https://github.com/blockstack/blockstack.js/blob/v21.1.1/src/operations/skeletons.ts#L729

I'm assuming the correct format is the one in the implementation, but the mismatch is certainly confusing in this case

**Comment by moxiegirl** [comment]
@alexmavr Thank you for the error report. @jcnelson can you confirm the error and correction offerred?

**Comment by alexmavr** [comment]
I confirmed that a Big Endian amount is used in core by manually constructing a transaction that uses 8-byte BE encoding and broadcasting it on the network

**Comment by alexmavr** [comment]
This is still applicable
