### ISSUE TITLE
Formalize the Gaia image that Freidger produced

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs#446]
![Blockstack Storage(5)](https://user-images.githubusercontent.com/1347209/68599691-dde93180-0455-11ea-961f-6621cc4c6365.png)

**Comment by friedger** [comment]
@moxiegirl What needs to be done here?

**Comment by moxiegirl** [comment]
@friedger It needs to fit with our existing graphic style...like on this page:https://docs.blockstack.org/storage/overview.html

**Comment by friedger** [comment]
@agraebe Is this kind of diagram still interesting? Or too complicated? Why was it closed?

**Comment by agraebe** [comment]
I think this was a "bulk closure" of tickets. I'm seeing it for the first time - I think it can be slightly simplified and use our branding. would be very nice to have an illustration like this

cc @jasperjansz
