### ISSUE TITLE
Update to Wallet FAQ

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/docs#474]
Update to https://docs.blockstack.org/org/wallet-troubleshoot.html#change-from-a-software-only-wallet-to-a-hardware-wallet 

To this

If you have a supported hardware device (Trezor - excluding Model T - and Ledger), you can restore the wallet with your seed phrase using the instructions below

1. Plug in your hardware wallet, 
2. Reset/restore using that wallet's system (e.g., for trezor: https://wiki.trezor.io/User_manual:Recovery#Recovery_process)
Trezor Wiki - https://wiki.trezor.io/images/Wallet_initializing_device.png
For Ledger: https://support.ledger.com/hc/en-us/articles/360005835414-Initialize-your-device
3. Once that is complete, download the updated Stacks Wallet software from https://wallet.blockstack.org/
4. Plug in the Trezor/Ledger the hardware device
5. Install the Stacks Wallet software choosing "Restore a wallet" during that process

**Comment by moxiegirl** [comment]
@ryanarndtcm Instructions aren't appropriate for an FAQ.  I will add these instructions to the document. For an FAQ, I will provide a reference to that document.

**Comment by ryanarndtcm** [comment]
That makes good sense. Thank you for the clarification and help, Mary!

**Comment by agraebe** [comment]
this is outdated
