### ISSUE TITLE
Unclear tuple specification

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs#496]
The [Clarity reference](https://docs.blockstack.org/core/smart/clarityref#tuple) specifies that a `tuple` is constructed using the following syntax:

    (tuple ((key0 expr0) (key1 expr1) ...))

However, the provided example disagrees:

    (tuple (name "blockstack") (id 1337))

**Comment by friedger** [comment]
This is the correct format `(tuple (key0 expr0) (key1 expr1) ...)` or the short form `((key0 expr0) (key1 expr1) ...)`

Not sure in which branch the current doc is sitting on blockstack-core. @moxiegirl ?

**Comment by njordhov** [comment]
Also, the reference says `tuple` is a _function_. However, by convention the arguments to functions are resolved before function invocation. Arguments like `(key0 expr0)` are not function calls nor forms that evaluates. Hence, as is, `tuple` is a special form, akin to a macro, rather than a function.

**Comment by friedger** [comment]
working on it at blockstack/stacks-blockchain#2023
