### ISSUE TITLE
Clarity: Fold with non-associative combination function

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs#511]
The Clarity [fold](https://docs.blockstack.org/core/smart/clarityref#fold) function is defined as:

> The fold function applies the input function func to each element of the input list and the output of the previous application of the fold function. When invoked on the first list element, it uses the initial-value as the second input. fold returns the last value return by the successive applications.

The reference has examples of using fold with the associative `*` to multiply. However, according to the definition, such a _right fold_ will have perhaps surprising results when used with a non-associative combination function, such as `-` to subtract. Assuming this is the intended behavior, there should be relevant examples, e.g.:

```clojure 
(fold - (list 3 7 11) 2)   ;; Returns 5 by calculating (- 11 (- 7 (- 3 2)))
(fold concat "cdef" "ab")   ;; Returns "fedcab"
(fold concat (list "cd" "ef") "ab")   ;; Returns "efcdab"
```

Also, `fold` in Clarity is not actually a _function_ but rather a _special form_, as per the [fold implementation](https://github.com/blockstack/blockstack-core/blob/222f545b49f895c90b82291573f1f32cf94608b5/src/vm/functions/iterables.rs) the first argument has to be a literal function name rather than an expression that evaluates to a function. This should be mentioned in the documentation as it deviates from what developers would expect.

**Comment by kantai** [comment]
Thanks for bringing this up @njordhov -- the function docs should definitely be updated. We'd be happy to review a PR for a doc update in `src/vm/docs/mod.rs`!
