### ISSUE TITLE
as-max-len throws type error

### ISSUE THREAD

**Issue by Trudko** [blockstack/docs#605]
Seems like [documentation](https://docs.blockstack.org/core/smart/clarityref#as-max-len) has a typo for as-max-len. 

Sample code:

`
(define-public (foobar)   
   (ok (as-max-len? (list 2 2 2) 3))
)
`

run via test:

`
 const query = helloWorldClient.createQuery({
                method: { name: "foobar", args: [] },
            });
const receipt = await helloWorldClient.submitQuery(query);
const result = Result.unwrapString(receipt);
`

Throws an error TypeError(UIntType, IntType). Using u3 instead of 3 works.

**Comment by friedger** [comment]
Already fixed in https://github.com/blockstack/stacks-blockchain/commit/96468e39240ef10515f5b2a4c7ff5ce87e2c6fc6 

Docs should be re-generated from there.

**Comment by johndmulhausen** [comment]
Indeed it has, thank you @friedger
