### ISSUE TITLE
Guide: Integrate Stacks

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#614]
Suggesting we have a guide for those wishing to understand the basics of Stacks transactions with the likely aim of integrating with a wallet or exchange. Could be as extensive as: https://github.com/blockstack/stacks-transactions-js/blob/master/README.md with more basic info about Stacks transactions/formats. Or, could only cover the basics of transactions and send/receive. 

@yknl maybe you have some opinions on this. Someone who wanted to learn the basics + integrate – where would you send them today?

**Comment by yknl** [comment]
We should create a full Stacks integration guide that covers everything from Stacks blockchain basics to transactions. This could live as a separate section in the docs.

**Comment by johndmulhausen** [comment]
https://paper.dropbox.com/doc/wyvZRBd6DpfhVsIfRuB65

Turn this into a real doc

**Comment by johndmulhausen** [comment]
Needs to include websocket endpoint details which we haven't touched yet
