### ISSUE TITLE
Automating Clarity Ref Updates

### ISSUE THREAD

**Issue by kantai** [blockstack/docs#618]
`clarityRef.json` is generated by the docgen command in the stacks-blockchain repo -- should we setup some kind of automation to make sure that when that command updates the JSON, either the site here gets updated automatically, or it triggers something like an automatic PR?

**Comment by kantai** [comment]
Also related, this PR https://github.com/blockstack/stacks-blockchain/pull/1507 deletes most of the duplicated docs content from the stacks-blockchain repo, however, it's kind of hung up on discussion of the stacks-blockchain's API documentation. We want the API interface to be documented at least in the stacks-blockchain repo, but see that the content needs to get over here as well somehow.

I think that presents us with three options:

1. Someone manually opens a PR on this repo any time there's a change in either the docgen output or the RPC API on the stacks-blockchain's main branch.
2. We use some kind of (Github action?) magic to automate the process of opening that PR.
3. The docs website's build automatically pulls the data from the stacks-blockchain's main branch.

**Comment by agraebe** [comment]
this was done already
