### ISSUE TITLE
Standardize language around writing/building/developing smart contracts

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs#620]
![image](https://user-images.githubusercontent.com/25477905/85132240-a555d580-b238-11ea-8ca9-3492f2f63ff6.png)

![image](https://user-images.githubusercontent.com/25477905/85132255-ac7ce380-b238-11ea-8133-5229be7d378d.png)

We're using three different verbs in the same flow. I suggest we stick to 1 term. instead

**Comment by agraebe** [comment]
We could even use Vale (the automated style checker) to comment on usage that wouldn't align with our defined standard.

First, we should agree on the standard to go with. Please chime in! 

I'd vote for "writing smart contracts". Developing or building sounds like it might be a broader scope.
