### ISSUE TITLE
Incorrect faucet links and related errors

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs#622]
Based on an error reported [by `Luke | MXC` in Discord](https://discordapp.com/channels/621759717756370964/691807645291642961/723862616228888648), the faucet address [listed in the tutorial](https://github.com/blockstack/docs.blockstack/blob/master/_core/smart/tutorial.md#get-familiar-with-cli-optional) returns a 302 temporary redirect that doesn't process using `json_pp`.

Command I used:

```
curl -X POST "https://sidecar.staging.car/v1/debug/faucet?address=ST3MJ5JT7KH58ZB54JKEEW7E7XX4JPVKAK8RWSMG0" | json_pp
```

Error received:

```
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Temporary Redirect. ...") at /usr/bin/json_pp line 45.
```

Actual response without `json_pp`:

```
Temporary Redirect. Redirecting to ../faucets/stx?address=ST3MJ5JT7KH58ZB54JKEEW7E7XX4JPVKAK8RWSMG0
```

Since this is similar to the commands I've used with the BTC faucet, I tried hitting the redirect URL directly and still received an error:

```
curl -X POST "https://sidecar.staging.blockstack.xyz/sidecar/v1/faucets/stx?address=ST3MJ5JT7KH58ZB54JKEEW7E7XX4JPVKAK8RWSMG0" | json_pp
```

```json
{
   "errorTag" : "1ef50427-cca4-440d-bc8a-5806c0a889b0",
   "stack" : "FetchError: request to http://stacks-node-follower.staging-argon.svc.cluster.local:20443/v2/fees/transfer failed, reason: connect ECONNREFUSED 10.1.233.163:20443\n    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1455:11)\n    at ClientRequest.emit (events.js:315:20)\n    at Socket.socketErrorListener (_http_client.js:432:9)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:84:8)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
   "error" : "FetchError: request to http://stacks-node-follower.staging-argon.svc.cluster.local:20443/v2/fees/transfer failed, reason: connect ECONNREFUSED 10.1.233.163:20443"
}

```

**Comment by ltfschoen** [comment]
In the interim, I discovered that I can obtain Testnet STX tokens for a specific address by requesting it from https://testnet.blockstack.org/faucet, after following these steps: https://docs.blockstack.org/core/smart/cli-wallet-quickstart.html#getting-tokens

**Comment by agraebe** [comment]
this was fixed now
