### ISSUE TITLE
Mining Stacks Guide

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#631]
- Introduction to Stacks mining. Running a miner (own page for [this section](https://docs.blockstack.org/core/smart/testnet-node.html#running-a-miner))
    - Create “Mainnet” version, put in “Stacks Tokens” section
    - Running on testnet before running on Mainnet

**Comment by johndmulhausen** [comment]
Have top-level node for mining (call out testnet use case as well). Hank is the SME.

**Comment by agraebe** [comment]
this could include machine requirements to run a miner and/or to run a full node

**Comment by agraebe** [comment]
closing in favor of https://github.com/blockstack/docs/issues/824
