### ISSUE TITLE
Remove user-facing wallet docs

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#633]
- Nuke current Wallet stuff that is user-facing
- Focus remains on developers who are going to create their own wallets
- Integration docs will come from hardware wallet partners

**Comment by markmhx** [comment]
I'm thinking all these pages can be removed:

- https://docs.blockstack.org/org/secureref.html
- https://docs.blockstack.org/org/tokenholders.html
- https://docs.blockstack.org/org/wallet-troubleshoot.html
- https://docs.blockstack.org/org/wallet-use.html
- https://docs.blockstack.org/org/wallet-install.html
- https://docs.blockstack.org/org/wallet-intro.html
- https://docs.blockstack.org/org/token.html

@jeffdomke that look right to you?

**Comment by agraebe** [comment]
This seems to be mostly a task to delete existing content. If there's more context, please let me know.
