### ISSUE TITLE
Guide to using the Stacks Blockchain API

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#636]
We have the sidecar API reference, but perhaps more of a high-level guide that calls out how to get set up using the API and call some of the most core functions would be helpful.

**Comment by markmhx** [comment]
Note that in support of https://github.com/blockstack/docs.blockstack/issues/608 developers could specifically use guidance on how to check transaction status in particular using an ID.

**Comment by agraebe** [comment]
closing. this is now part of #614

**Comment by agraebe** [comment]
On some occasions in the past (see the history of this issue), we wanted to include a **guide** specifically for the [Stacks Blockchain API](https://docs.blockstack.org/references/stacks-blockchain-api). So far, we have references and tutorials. What is missing is some general explanation of the API (not goal-oriented, but purely describing the functionality). That could include the following chapters:

- Spinning up your own API server
- Clarity value in JSON format
- Error handling / response types
- Pagination
- Proofs
- OpenAPI spec
- Client library overview (including WebSockets, and TS type generation)
- Postman collection
- Generation of client libraries for other languages
- Proxies RPC endpoints
- BTC relationship between txs/blocks
- Search
- Rosetta support
