### ISSUE TITLE
Stacking guide

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#637]
Stacking guide (exec summary of SIP007)
https://github.com/blockstack/stacks-blockchain/blob/develop/sip/sip-007-stacking-consensus.md

**Comment by agraebe** [comment]
relevant PR: https://github.com/blockstack/stacks-blockchain/pull/1790

**Comment by kantai** [comment]
I put together something along the lines of a runbook for getting started with Stacking on the testnet:

https://gist.github.com/kantai/c261ca04114231f0f6a7ce34f0d2499b

Not sure where this documentation should end up landing (or if there's someone already working on this), but I figured it might be useful here.

**Comment by agraebe** [comment]
@kantai thanks for sharing! I'll capture the steps in the #755 PR once I verified them. I'll use the stacks2.0 CLI though to be consistent within the docs
