### ISSUE TITLE
Update Blockstack overview page 

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#650]
https://docs.blockstack.org/org/overview.html

We're now linking to this page from the blockstack.org homepage, so it's worth taking a look at updating it generally to ensure it explains PBC and the Stacks ecosystem in the right terms.

**Comment by cuevasm** [comment]
I'm going to merge this over into a ticket with the rebrand stuff.

**Comment by cuevasm** [comment]
https://github.com/blockstackpbc/design/issues/119
