### ISSUE TITLE
Feature: Copy code sample to clipboard

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#663]

**Comment by aulneau** [comment]
@johndmulhausen here is the general strategy i would suggest for taking this on:
 
- [see `children` here ](https://github.com/blockstack/docs.blockstack/blob/feat/next/src/components/mdx/components/code.tsx#L88) -> to learn more about children, [read this](https://mxstbr.blog/2017/02/react-children-deepdive/)
- use this util to get the text of the code block -> [onlyText](https://github.com/blockstack/docs.blockstack/blob/feat/next/src/common/utils/index.ts#L45)
- use the `useClipboard` hook to enable copying of the value, [see here](https://github.com/blockstack/ux/blob/master/packages/ui/src/use-clipboard/index.tsx) (see implementation example [here](https://github.com/blockstack/docs.blockstack/blob/feat/next/src/components/mdx/components/heading.tsx#L19))
- add a button to copy it
- ???
- profit!
