### ISSUE TITLE
Was this page helpful? section improvements

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs#686]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/e665b1de-9e3a-4c26-afd4-ed030476e725)

- Align the edges with the content
- Icons draw too much attention because they're too large. Should be 28px instead of 42px
- Icons missing background, attached svgs!

[Happy.svg](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/5f4f2a40-2ff3-4cf5-8f41-d0f75fe8cf12)![Neutral.svg](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/1a41ce85-55b4-489d-8314-f25381011c15)![Sad.svg](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/8efc4c31-4f16-4173-b490-5f9576ba7892)

**Comment by aulneau** [comment]
@jasperjansz these are react components, the background is missing only on accident when I was making it work with dark mode. Could you design a dark mode version of the faces I can use? Thanks!
