### ISSUE TITLE
Blank results in Algolia search

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs#690]
![image](https://user-images.githubusercontent.com/25477905/89429211-96ba7380-d73d-11ea-8008-2102dd0afbab.png)

https://docsearch.algolia.com/docs/tips/

**Comment by jasperjansz** [comment]
Looking into this more this is probably because these pages are blank: 
![image](https://user-images.githubusercontent.com/25477905/89429351-bbaee680-d73d-11ea-81d1-9225997780b9.png)

Feel free to close if that's the case

**Comment by aulneau** [comment]
Search will be disabled on launch, and re-enabled 24-48hrs after launch so they can re-index the new site.
