### ISSUE TITLE
Suggestion: focus on Web-related use-cases for smart contracts

### ISSUE THREAD

**Issue by jcnelson** [blockstack/docs#697]
Not a show-stopping problem, but if I may be frank, the intro to Clarity page [1] sounds like a re-hashing of a lot of old ideas from the smart contract platforms of yesteryear.  It doesn't help me understand why smart contracts need to exist on a Can't-Be-Evil web (like, what superpowers do they give me as an app developer?), nor does it help me understand why I would want a smart contract if my app doesn't have some kind of token.  Also, is there any _real_ use-case of a blockchain helping automate a supply chain? ;)

I'd suggest focusing on making this page answer the following two questions:
* What novel capability does a smart contract give a Blockstack app, that could not be had with PaaS today?  Payments are superior on PaaS today in every conceivable way compare to Bitcoin, so this rules out any sort of "pay for service" use-case.
* Why should a user want to interact with a smart contract?

Regarding the first, I think the main use-case for smart contracts in Blockstack is to offer an alternative to AWS Lambda.  Many apps you'd like to build in Blockstack have some kind of _shared global state_ that anyone can nominally write to.  But crucially, this state doesn't need to be very big, nor does there need to be very much computing done on it on the write path -- you can do _a lot_ with just a handful of POST handlers that authorize writes to a shared key/value map.  This is _exactly_ what Clarity provides:  a way to publish a tiny serverless function with a small amount of state, whereby reads are instantaneous and free for the developer (the user hits their own node), but writes are expensive (either the user pays via a transaction fee, or the developer pays via a sponsored transaction).

For example, you could build something like Imgur with just Gaia and Clarity.  You'd have a smart contract that lets anyone publish a photo album via a transaction, and you'd use the `(define-read-only ..)` Clarity keyword to create a read-only RESTful API for it that your app client can use to walk the list of published albums in a time-series fashion (recall that the Stacks node can service HTTP requests that call read-only Clarity functions).  The album itself can be as big as you want and have arbitrary depth -- it simply lives in Gaia.

In this example, it's clear how Clarity is helping establish a Can't-Be-Evil Web:  there's no server that someone has to keep online to make photo albums discoverable; users retain all authoritative copies of their data (and can even delete them simply by erasing them from Gaia); anyone can publish a photo album without Imgur's permission.  It's also a big win for the developer when compared to AWS Lambda:  the developer only needs to pay the one-time fee to publish the smart contract (instead of recurring fees).  Users pay for service there on in; the developer can just walk away afterwards and the app will remain usable as long as at least one user cares about it.  But, just like AWS Lambda, the smart contract won't ever go offline or need to be maintained -- there's no outages or server maintenance to worry about (it's the network's problem, not the developer's problem).

To answer the second point, most of the time the user doesn't know if they're interacting with a smart contract.  Specifically, reading state out of a smart contract is just a (free) HTTP request.  Only when the user goes to publish a photo album will the user need to go and send a transaction.  And even then, because Stacks offers sponsored transactions, the user doesn't need to pay with STX or even be intimately familiar with cryptocurrencies -- the user just needs to relay it through a transaction sponsor (which can be automatic and painless -- the developer may provide this at first to grow the app, but the developer may later make it so the user just picks one within the app client).  Crucially, the fact that sponsored transactions exist means that the developer _could_ put a sponsor service in a commodity PaaS, and use a commodity payment processor to bill the user _in their preferred currency_ for service!  But, this doesn't detract from the power offered to the developer and user with Clarity, since Clarity is solving a different problem altogether from payment processing.

[1] https://blockstack-docs-git-feat-next.blockstack.vercel.app/smart-contracts/overview

**Comment by hstove** [comment]
Love your thoughts, Jude. You highlight the potential of sponsored transactions. I want to +100 this, and would request that we put proper time into documentation around setting up sponsored transactions. This is a way to provide excellent UX in Clarity apps, as Jude mentioned - the user doesn't even have to know that they're using a smart contract.
