### ISSUE TITLE
Improve clarity tmLanguage 

### ISSUE THREAD

**Issue by aulneau** [blockstack/docs#703]
For the docs we are using [`shiki`](https://github.com/octref/shiki) for code highlighting, which highlights code with the same engine that vscode uses. They use a `tmLanguage.json` file for their definitions. I generated one based off of the vscode clarity extension, but it seems to highlight code slightly differently than the [Prism Clarity definition we have here](https://github.com/blockstack/ux/blob/master/packages/ui/src/highlighter/language-definition.tsx).

### tmLanguage definition:
```json
{
  "fileTypes": [
    "clar"
  ],
  "keyEquivalent": "^~S",
  "name": "Clarity",
  "patterns": [
    {
      "include": "#comment"
    },
    {
      "include": "#sexp"
    },
    {
      "include": "#string"
    },
    {
      "include": "#language-functions"
    },
    {
      "include": "#illegal"
    }
  ],
  "repository": {
    "comment": {
      "begin": "(^[ \\t]+)?(?=;)",
      "beginCaptures": {
        "1": {
          "name": "punctuation.whitespace.comment.leading.clarity"
        }
      },
      "end": "(?!\\G)",
      "patterns": [
        {
          "begin": ";",
          "beginCaptures": {
            "0": {
              "name": "punctuation.definition.comment.clarity"
            }
          },
          "end": "\\n",
          "name": "comment.line.semicolon.clarity"
        }
      ]
    },
    "define-map": {
      "begin": "(?<=\\()(define-map)\\s([[:alnum:]][[:alnum:]!$%&*+-./:<=>?@^_~]*)\\s+",
      "end": "(?=\\))",
      "captures": {
        "1": {
          "name": "keyword.control.clarity"
        },
        "2": {
          "name": "entity.name.function.clarity"
        }
      },
      "name": "meta.declaration.map.clarity",
      "patterns": [
        {
          "include": "#comment"
        },
        {
          "include": "#sexp"
        },
        {
          "include": "#illegal"
        }
      ]
    },
    "constants": {
      "patterns": [
        {
          "match": "\\'(true|false)",
          "name": "constant.language.boolean.clarity"
        },
        {
          "match": "(?<=[\\(\\s])((#e|#i)?[0-9]+(\\.[0-9]+)?|(#x)[0-9a-fA-F]+|(#o)[0-7]+|(#b)[01]+)(?=[\\s;()'\",\\[\\]])",
          "name": "constant.numeric.clarity"
        },
        {
          "match": "\\'[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{28,41}",
          "name": "constant.numeric.clarity"
        }
      ]
    },
    "illegal": {
      "match": "[()\\[\\]]",
      "name": "invalid.illegal.parenthesis.clarity"
    },
    "language-functions": {
      "patterns": [
        {
          "match": "(?x)  (?<=(\\s|\\()) # preceded by space or (\\n\n  ( or|and|xor|not|begin|let|if|ok|err|\n    unwrap!|unwrap-err!|unwrap-panic|unwrap-err-panic|match|try!|asserts!\n    map-get\\?|var-get|contract-map-get\\?|get|tuple|\n    define-public|define-private|define-constant|define-map|define-data-var|\n    define-fungible-token|define-non-fungible-token|\n    define-read-only|let\\* )\n  (?=(\\s|\\())\n",
          "name": "keyword.control.clarity"
        },
        {
          "match": "(?x)  (?<=(\\s|\\()) # preceded by space or (\n  ( is-eq|is-some|is-none|is-ok|is-err )\n  (?=(\\s|\\()) # followed by space or (\n",
          "name": "support.function.boolean-test.clarity"
        },
        {
          "match": "(?x)  (?<=(\\s|\\()) # preceded by space or (\n  ( var-set|map-set|map-delete|map-insert|\n    ft-transfer\\?|nft-transfer\\?|nft-mint\\?|ft-mint\\?|nft-get-owner\\?|ft-get-balance\\?|\n    contract-call\\? )\n  (?=(\\s|\\()) # followed by space or (\n",
          "name": "support.function.with-side-effects.clarity"
        },
        {
          "match": "(?x)  (?<=(\\s|\\()) # preceded by space or (\n  ( as-contract|contract-caller|tx-sender|block-height|at-block|get-block-info\\? )\n  (?=(\\s|\\()) # followed by space or (\n",
          "name": "support.function.sender-context.clarity"
        },
        {
          "match": "(?x)  (?<=(\\s|\\()) # preceded by space or (\n  ( >=?|<=?|[*/+-]|mod|pow )\n  (?=(\\s|\\()) # followed by space or (\n",
          "name": "support.function.arithmetic.clarity"
        },
        {
          "match": "(?x)  (?<=(\\s|\\()) # preceded by space or (\n  ( list|map|filter|fold|len|concat|append|as-max-len\\?|to-int|to-uint|\n    buff|hash160|sha256|sha512|sha512/256|keccak256 )\n  (?=(\\s|\\()) # followed by space or (\n",
          "name": "support.function.general.clarity"
        }
      ]
    },
    "sexp": {
      "begin": "\\(",
      "beginCaptures": {
        "1": {
          "name": "punctuation.section.expression.begin.clarity"
        }
      },
      "end": "\\)(\\n)?",
      "endCaptures": {
        "1": {
          "name": "punctuation.section.expression.end.clarity"
        },
        "2": {
          "name": "meta.after-expression.clarity"
        }
      },
      "name": "meta.expression.clarity",
      "patterns": [
        {
          "include": "#comment"
        },
        {
          "include": "#define-map"
        },
        {
          "begin": "(?x) (?<=\\() # preceded by (  (define-public|define-private|define-constant|define-read-only)\\s+\n  \\(    # open parens\n    ([[:alnum:]][[:alnum:]!$%&*+-./:<=>?@^_~]*)\n    ((\\s+\n      \\( # open parens for parameter/type pair\n      \\s*\n      ([[:alnum:]][[:alnum:]!$%&*+-./:<=>?@^_~]*)\n      \\s+\n      ([[:alnum:]][[:alnum:]!$%&*+-./:<=>?@^_~]*)\n      \\s*\n      \\) # close parens for parameter/type pair\n      \\s*\n      )*)\n    \\s*\n  \\)    # close parens\n",
          "captures": {
            "1": {
              "name": "keyword.control.clarity"
            },
            "2": {
              "name": "entity.name.function.clarity"
            },
            "4": {
              "name": "variable.parameter.function.clarity"
            }
          },
          "end": "(?=\\))",
          "name": "meta.declaration.procedure.clarity",
          "patterns": [
            {
              "include": "#comment"
            },
            {
              "include": "#sexp"
            },
            {
              "include": "#illegal"
            }
          ]
        },
        {
          "begin": "(?<=\\()(define)\\s([[:alnum:]][[:alnum:]!$%&*+-./:<=>?@^_~]*)\\s*.*?",
          "captures": {
            "1": {
              "name": "keyword.control.clarity"
            },
            "2": {
              "name": "variable.other.clarity"
            }
          },
          "end": "(?=\\))",
          "name": "meta.declaration.variable.clarity",
          "patterns": [
            {
              "include": "#constants"
            },
            {
              "include": "#comment"
            },
            {
              "include": "#sexp"
            },
            {
              "include": "#illegal"
            }
          ]
        },
        {
          "include": "#language-functions"
        },
        {
          "include": "#string"
        },
        {
          "include": "#constants"
        },
        {
          "match": "(?<=[\\(\\s])(#\\\\)(space|newline|tab)(?=[\\s\\)])",
          "name": "constant.character.named.clarity"
        },
        {
          "match": "(?<=[\\(\\s])(#\\\\)x[0-9A-F]{2,4}(?=[\\s\\)])",
          "name": "constant.character.hex-literal.clarity"
        },
        {
          "match": "(?<=[\\(\\s])(#\\\\).(?=[\\s\\)])",
          "name": "constant.character.escape.clarity"
        },
        {
          "include": "#sexp"
        },
        {
          "include": "#illegal"
        }
      ]
    },
    "string": {
      "begin": "(\")",
      "beginCaptures": {
        "1": {
          "name": "punctuation.definition.string.begin.clarity"
        }
      },
      "end": "(\")",
      "endCaptures": {
        "1": {
          "name": "punctuation.definition.string.end.clarity"
        }
      },
      "name": "string.quoted.double.clarity",
      "patterns": [
        {
          "match": "\\\\.",
          "name": "constant.character.escape.clarity"
        }
      ]
    }
  },
  "scopeName": "source.clarity",
  "uuid": "a26370fe-ce63-4d00-a5f7-a00abb11be89"
}
```

@lgalabru or @kantai would either of you be able to compare the two, and make modifications to the `tmLanguage` json object to reflect what is in the Prism definition? Would be greatly appreciated, I took a stab at it but it's a bit beyond me, and would probably be much more effective if either of you did it.

Thanks

**Comment by kantai** [comment]
Yep, @aulneau, I'll take a look at this today.

**Comment by aulneau** [comment]
Thanks @kantai :)

**Comment by kantai** [comment]
@aulneau -- do you have a branch where you've built shiki with the tmLanguage spec? I'd like to just get a comparison of the tmLanguage output and the prism output.

**Comment by aulneau** [comment]
@kantai do you mean you need a visual output? if so can you provide me with a contract that has all you need in it?

**Comment by aulneau** [comment]
@kantai here is an example: 
![Group 1703](https://user-images.githubusercontent.com/11803153/90046006-763a6e00-dc95-11ea-994a-1a5a35c73feb.png)

docs.blockstack.org is currently using shiki, and testnet-explorer.blockstack.org is using prism

**Comment by aulneau** [comment]
@kantai if you want to test it on your own:

- clone this: https://github.com/aulneau/unified-vscode
- install [yalc](https://github.com/whitecolor/yalc)
- clone docs: https://github.com/blockstack/docs

in unified-vscode
- yarn
- when you want to test (after changes) run `yalc publish --push`
- the language is located here: `/src/shiki/data/extraGrammars/clarity.tmLanguage.json`

in docs:
- `yarn && yalc add unified-vscode`
- `yarn dev`
- navigate to http://localhost:3000/smart-contracts/principals

That should do it. I am also happy to test as I have it all set up already!

**Comment by kantai** [comment]
> @kantai here is an example:

That's perfect, thanks

**Comment by kantai** [comment]
I opened a PR that improves the `clarity.tmLanguage.json` file a bit -- it doesn't _exactly_ match the output of the prism grammar. The prism grammar matches _all_ function applications and highlights the first entry in the application, e.g., in the expression `(a b c)`, `a` would always be highlighted. Replicating that in tmLanguage syntax is tricky.

In any case, I think it's reasonable to expect that there would be some difference between the two highlighting libraries -- they are two more or less completely different definitions, so if we wanted to maintain consistency across the board, it'd be better to use only one of the libraries.

**Comment by aulneau** [comment]
Thank you @kantai!

> In any case, I think it's reasonable to expect that there would be some difference between the two highlighting libraries -- they are two more or less completely different definitions, so if we wanted to maintain consistency across the board, it'd be better to use only one of the libraries.

I see your point, but I am curious: the `tmLanguage` file was originally generated via the [VS Code extension for clarity](https://github.com/blockstack/clarity-vscode/blob/master/syntaxes/clarity.yaml). This is something that I feel like we should continue to support for different reasons.

Additionally, the Prism language definition is useful for dynamic code highlighting, such as client side code. Shiki / any other vscode based highlighter can only work at build/run time due to some dependencies on a regex library, but generally gives a better highlight than prism/other client side highlighting tools (and also removes the need to bundle any code for it).

Overtime do you see us needing to update the language definitions?

**Comment by kantai** [comment]
Yes, I see these both requiring some maintenance over time -- even once the Clarity language remains stable, people improve highlighters all the time.

As for maintaining both of them -- I think it will be challenging to keep them in sync with one another, and we should just be prepared for there to be some differences between them over time. For example, if someone submitted a PR on the vscode-extension repo with support for parsing the `{ }` syntax for tuples, we probably wouldn't require them to also update the Prism library. Different highlighting libraries end up having different outputs for the source code all the time (for a whole host of reasons, but one of the biggest is that all these libraries have different ways of describing a grammar, so it's hard to port changes in one grammar definition to another one).

**Comment by aulneau** [comment]
Yep, def agree. Thank you for adding more context. Hopefully in the future we will have community made/supported definitions for all popular highlighting libraries because everyone will be using clarity :)
