### ISSUE TITLE
Inconsistent link styles in main nav

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#704]
We currently underline on hover: headers & links in content and in "on this page". But we don't underline links in the main nav. The hover states of the main nav items are also different.

It would be great to have the same link styles, so users don't get confused about what is clickable or not.

**Comment by aulneau** [comment]
Can you please include what you think should be different? The main nav is made to replicate the nav of blockstack.org

**Comment by agraebe** [comment]
I updated the description. @jasperjansz's opinion would be great
