### ISSUE TITLE
Use blocksurvey for feedback tool

### ISSUE THREAD

**Issue by aulneau** [blockstack/docs#710]

**Comment by agraebe** [comment]
What's happening with the current submissions? I think the way the component works suggests one could provide a sentiment before opening a form. Seems like this might require some thoughts.

If the current setup works, maybe we could keep it? I'd assume low participation and hence low priority for this. Wdyt?

**Comment by aulneau** [comment]
They are being fed to my account I set up with the tool we are using. I only have two bits of feedback -- from you and @hstove  ;). It's a good tool but I like that we are using blocksurvey in our explorer feedback, and think we should do the same here.

While I agree that it would be best to be able to capture when someone hits any of the buttons, but unfortunately I don't currently know a good solution. I'd love for blocksurvey to be able to have an API endpoint we can hit, but I don't think they offer that.

**Comment by agraebe** [comment]
I agree. I just checked out their FAQs to see if there'd be a way to pass a parameter to the survey (eg to indicate what button was pressed on the docs) but I couldn't find anything relevant. Still, agree that we should use the same tools across properties

**Comment by wilsonbright** [comment]
I just checked this. This is Wilson from Blocksurvey. Few weeks ago, we have release a query parameters / hidden variables on URL. By this sentiment can be captured by constructing variables like ?sentiment=positive. This will added to the result as well without user entering it. Would this be helpful?

**Comment by agraebe** [comment]
hey @wilsonbright. oh, that would totally do the trick! is that already live? How will the data show in the results?

**Comment by wilsonbright** [comment]
hi @agraebe, the data will be the grid as a variable with values. Enclosing a sample screenshot. The 'source' and 'group' are passed in URL. Sample URL for trial. https://blocksurvey.io/survey/1DnQ8ArNjQU8Xrf97BbaNNLbFeJTksxHYC/a4e4ee71-ea74-4f5e-a188-b8ef40ab4406?source=twitter&group=binance

Not sure if this will be helpful when it comes to user experience. But, we can look into building small widgets to capture data for docs site specifically. I have made note of this. 

![Screenshot from 2020-09-14 21-15-03](https://user-images.githubusercontent.com/10022551/93107845-c14e0380-f6cf-11ea-9b9a-f3ae2bf49f0e.png)

**Comment by agraebe** [comment]
@wilsonbright that's great!

@aulneau looks like this will be a good solution. let's see how/when to prioritize this

**Comment by aulneau** [comment]
@wilsonbright This looks cool. I think an ideal feature would be: allow for sentiment to be captured, eg good/neutral/bad without the user submitting anything, eg, they would click on an item, and then we can do a POST request for the item they hit. Would that be possible?

**Comment by wilsonbright** [comment]
@aulneau Can you share your mail id to 'contact@blocksurvey.org'. Will share details on how this can be done through POST request.

**Comment by wilsonbright** [comment]
Hi @aulneau and @agraebe, we have recently added docs on using BlockSurvey as a headless form builder. Here is a sample for reference: https://help.blocksurvey.io/article/99-how-to-use-blocksurvey-as-headless-forms
