### ISSUE TITLE
Authentication Index Page Revamp

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#714]
Re: https://docs.blockstack.org/authentication/overview
- Replace graphic that doesn't work in Dark Mode
- Rename as Authentication Architecture Reference; position as how to roll your authentication, how the auth protocol works under the hood when using ConnectJS
- Overview page should be new: Talk about decentralized identity and what it means to us

**Comment by markmhx** [comment]
Note related conversation on Discord: https://discord.com/channels/621759717756370964/623217767356694547/786978554734182440
