### ISSUE TITLE
Create pretty diagrams of the stack at a few detail levels

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#716]
In the index revamp meeting we identified that there is a lack of visual information orienting the user about where they are in the stack. We agreed that we need new diagrams that show the stack at the 1000-foot level and to zoom in on the specific areas (storage, auth, smart contracts/blockchain, BNS).

@jasperjansz agreed to take it on; assigning

**Comment by pgray-hiro** [comment]
For simplicity, I'm closing this issue as we are doing a lot of this work in #658
