### ISSUE TITLE
Integrated reference doc experience design

### ISSUE THREAD

**Issue by johndmulhausen** [blockstack/docs#732]
One outcome from a recent docs jam was that we identified that a design exercise needs to occur to implement a more integrated reference doc experience for:

**APIs**
We are inconsistent with how we handle APIs; in the Blockchain API case we use OpenAPI and can hand off to ReDoc, as we are here: https://blockstack.github.io/stacks-blockchain-api/
However we also have a Node RPC API that we document by hand/totally inline: https://docs.blockstack.org/references/stacks-rpc-api

**CLIs**
Currently we have a take on this but it has problems: https://docs.blockstack.org/references/blockstack-cli

**JS Libraries**
We're sending users over to a Typedoc site, but Typedoc can export JSON and Markdown we think, so how would we surface library functions in our docs?

**Comment by friedger** [comment]
I would build something similar to the clarity reference integration for the typedoc json, if you don't have any other input
