### ISSUE TITLE
Simplify rust installation instructions

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs#747]
Under the [Prerequisites](https://docs.blockstack.org/stacks-blockchain/testnet-node#prerequisites) section of the testnet-node setup, there is an easier way to install Rust with a single command.

The current procedure:

1. Run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Select option 1 to proceed (default)

To skip the second step and specify the default from the beginning, you could use a slight variation of the command:

1. Run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y`

This is what I use [in my testnet shell script](https://github.com/AbsorbingChaos/bks-setup-miner/blob/master/config-miner-argon.sh#L76), and is further documented in the [rustup-init shell script](https://github.com/rust-lang/rustup/blob/master/rustup-init.sh#L28).

```
The installer for rustup

USAGE:
    rustup-init [FLAGS] [OPTIONS]

FLAGS:
    -v, --verbose           Enable verbose output
    -q, --quiet             Disable progress output
    -y                      Disable confirmation prompt.
        --no-modify-path    Don't configure the PATH environment variable
    -h, --help              Prints help information
    -V, --version           Prints version information
```

**Comment by aulneau** [comment]
@whoabuddy thank you for this! if you are interested, it would be wonderful if you submitted a PR with these changes!

**Comment by whoabuddy** [comment]
@aulneau happy to help, drafting the PR now!
