### ISSUE TITLE
Rethink Clarity onboarding

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#749]
The last two developers tests indicated that the current intro and hello world tutorial has the following issues:
- lack of aha moment
- low amount of transferable/meaningful learnings around the language
- lack of clarity why a local setup & project is needed (most tasks are in the explorer)

We should rethink how we introduce developers to Clarity. I would suggest we [consider these principles](https://github.com/Felienne/hedy#design-goals) when doing so.

**Comment by agraebe** [comment]
@jdbender66 @GinaAbrams @cuevasm for reference :)

**Comment by GinaAbrams** [comment]
🙏

**Comment by agraebe** [comment]
I'll take a look at this now. If there's any input, please share. My thinking is to design a < 30 min onboarding process that will require _some_ effort but mostly would support articulating the benefits of the platform. Right now, it is purely a "get a contract deployed" step-by-step guide. While it helped folks to get it done, it didn't inspire nor did it leverage aha moments for new developers. I want to change it while trying to minimize the work we have to do on the product side.

@jeffdomke @muneeb-ali - any narrative that you'd like to see more of in the docs onboarding?
