### ISSUE TITLE
Transaction signing docs

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/docs#754]
We're missing documentation of how transaction signatures are formed. SIP-005 discusses signing, but doesn't go into implementation details.

The only authoritative source(s) right now are our [Rust](https://github.com/blockstack/stacks-blockchain/blob/cb75c8f9a555aff85eafc068909d9d573941775d/src/chainstate/stacks/auth.rs), and [JavaScript implementations.](https://github.com/blockstack/stacks-transactions-js/blob/master/src/signer.ts)

Feedback from the pbc team, @yknl, and external entities working on transaction signing have expressed difficulties finding the right information. This will be of growing importance as further parties build custodial STX features.

/cc @zondax @jleni @neithanmo having working to implement tx signing for the Ledger, if you have any specific feedback, it'd be really helpful in improving our docs

**Comment by agraebe** [comment]
@kyranjamie does this cover the things you were looking for: https://docs.blockstack.org/smart-contracts/signing-transactions? Please reopen this if not.

**Comment by kyranjamie** [comment]
These docs show developers building apps on the Stacks blockchain how to sign transactions.

It doesn't go into any detail how, the software mentioned, arrives at those given signatures.

The documentation in question should answer questions like:

- What hashing algorithms are used to sign a transaction?
- How are the signature bytes formatted?
 
Something like [how signatures are explained here for ethereum](https://yos.io/2018/11/16/ethereum-signatures/)

**Comment by agraebe** [comment]
@kyranjamie or @hstove - this seemed very relevant for docs week. would you be able to take this on?

**Comment by kyranjamie** [comment]
As discussed in docs call, 2020-11-24, the missing transaction signature details should likely be added to SIP-005. All the specifications that, for example, an exchange might need to correctly implement a transaction signing themselves.

**Comment by agraebe** [comment]
it seems we can close this issue in favor of changes in the SIP005. LMK if I got that wrong.
