### ISSUE TITLE
linked api documentation refers to legacy chain

### ISSUE THREAD

**Issue by dantrevino** [blockstack/docs#760]
The api doc linked to in the documentation is for legacy stacks-1.0 branch.  Its misleading to be included in current docs.

https://docs.blockstack.org/stacks-blockchain/install-api

Its linked in the sidebar, here: https://docs.blockstack.org/stacks-blockchain/overview

**Comment by agraebe** [comment]
This was fixed with the chapter redesign. The doc is now inside the "Stacks 1.0" category
