### ISSUE TITLE
Add API details for DID resolver

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#763]
Add API details for DID resolver.

As per this discussion: https://discord.com/channels/621759717756370964/750467085720617031/751125264024469635

cc @whoabuddy

**Comment by kantai** [comment]
For Stacks V1, this endpoint _is_ documented:

https://core.blockstack.org/#resolver-endpoints-resolve-did

For Stacks v2, we can't document this endpoint until it exists, so this issue should be related to that -- whenever we implement the BNS endpoints, we'll need to document them.

**Comment by kantai** [comment]
I had previously unassigned this, because I'm not (at least at the moment) working on this API, so I didn't think it made sense for me to be assigned to documenting it.

**Comment by agraebe** [comment]
ah, let me remove it from the docs week!
