### ISSUE TITLE
Improve command-click behavior for navigation

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#770]
When command-clicking some of the navigation links, the URL opens up in a new tab as desired, but the current tab also changes the navigation, which is undesired.

Separately, command-clicking the "Back" button doesn't open the previous page in a tab as desired, but rather changes the current tab's navigation to the previous page's, which is undesired.

![Kapture 2020-09-11 at 17 52 14](https://user-images.githubusercontent.com/28991/92947237-05cf6a00-f458-11ea-80de-580913b24dea.gif)

The would both be helpful to fix given how developers will likely want to open multiple pages at a time while they read up and cross-compare info.

**Comment by agraebe** [comment]
this is fixed now
