### ISSUE TITLE
Improve running testnet instructions

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/docs#802]
Right now we ask users to `cargo install --path ./testnet/stacks-node`. This will pull in dependencies from crates.io. To avoid discrepancies and dependency issues, we should instead instruct users to build how we do. Something like:

```
$ cargo build --workspace --bin stacks-node
# binary will be in target/debug/stacks-node
$ ./target/debug/stacks-node krypton
# release build
$ cargo build --workspace --release --bin stacks-node
# binary will be in target/release/stacks-node
```

**Comment by agraebe** [comment]
The markdown page impacted by this is this: https://github.com/blockstack/docs/blob/master/src/pages/stacks-blockchain/running-testnet-node.md

**Comment by LowNightSnack** [comment]
May I jump in and work on this?

**Comment by agraebe** [comment]
Absolutely @LowNightSnack. Please make your changes in a new branch and submit a PR. We require lint checks to pass before commit. Let me know if you have questions or anything else.
