### ISSUE TITLE
Clarity references: Split up page into sections

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#811]
The current [Clarity reference page](https://docs.blockstack.org/references/language-clarity) is pretty slow to load and difficult to navigate through (given the length of the content). It would be much simpler to split out the single page into its own category, with the following pages:

**Clarity Language**
- Intro (covers public functions and contract calls sections from the current page)
- Types
- Keywords
- Functions

cc @aulneau

**Comment by friedger** [comment]
And another page for special forms (#495) ?

**Comment by agraebe** [comment]
> And another page for special forms (#495) ?

yes, you are right!
