### ISSUE TITLE
FAQ's color is off for the dropdown questions

### ISSUE THREAD

**Issue by wileyj** [blockstack/docs#814]
On the page https://docs.blockstack.org/references/faqs/general-information
Each of the questions is in a gray block with white text (very hard to read). It doesn't appear any css/js is missing/not loaded from the console either. 

screenshot:
<img width="1083" alt="Screenshot 2020-10-09 at 11 33 10" src="https://user-images.githubusercontent.com/2847772/95602889-94b5af00-0a23-11eb-9c87-5e7ab166c8c3.png">

**Comment by agraebe** [comment]
this seems fixed
