### ISSUE TITLE
Guide for Clarity values

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#816]
The Clarity Type system is mostly documented in the references. We should better document types in the smart contract category. This guide should include:

- [ ] Type description for all types (including string)
- [ ] Type declaration / instantiation
- [ ] Type samples
- [ ] Encoding/Decoding details
- [ ] Library support
- [ ] Helper methods (cvToString, )

**Comment by friedger** [comment]
This might be helpful: https://github.com/blockstack/stacks.js/tree/master/packages/transactions#constructing-clarity-values
