### ISSUE TITLE
Stacks Mining summary

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#824]
Document technical mining details. The best place is likely the "Stacks Blockchain" overview: https://docs.blockstack.org/stacks-blockchain/overview#stacks-mining

Things to add:
- [ ] [miner reward maturity](https://github.com/blockstack/stacks-blockchain/blob/9b62cc3acee09060d73a9216bdbaae1cb7b0b543/src/chainstate/stacks/db/mod.rs#L500)

@kantai could you please share the details with me? I can make the PR and find the right place/format for it

**Comment by kantai** [comment]
I'm not sure I'm the best person to determine the full list of details that would be important to prospective miners -- I will spend some time trying to think of what details a miner might be interested in, but it may make more sense to gleam this list from actual prospective miners.

**Comment by agraebe** [comment]
I can ask miners on discord and potentially via email!

@muneeb-ali do you have some insights to share?

**Comment by kantai** [comment]
These seem to me to be the most important details for Stacks miners:

**Mining frequency**. A new Stacks block may be mined once per Bitcoin block. To be considered for mining a block, a miner must have a block commit included in a Bitcoin block. If a miner wishes to update their commitment after submission, they may use Bitcoin Replace-By-Fee.

**Coinbase Rewards.** Miners receive coinbase rewards for blocks they mine. These rewards are shared (proportional to the amount committed to) with an user burn support operations that support the block.

The reward amounts are:

1000 STX per block are released in the first 4 years of mining
500 STX per block are released during the following 4 years
250 Stacks tokens per block are released during the following 4 years
125 STX per block are released from then on indefinitely.

These "halvings" are synchronized with Bitcoin halvings.

**Transaction fees.** Miners receives Stacks fees for transactions mined in any block they produce.

For transactions mined in microblocks, the miner that produces the microblock receives 40% of the fees, while the miner that confirms the microblock receives 60% of the fees.

**Reward maturity.** Miner rewards take 100 blocks to mature.

**Mining with Proof-of-Transfer.**

Miners commit Bitcoin to _two_ addresses in every leader block commit. The amount committed to each address must be the same. The addresses are chosen from the current reward set of Stacking participants. The choice of addresses is done using a verifiable-random-function, and determining the correct two addresses for a given block requires monitoring the stacks chain.

100,000 Bitcoin blocks _after_ mining begins, the PoX sunset phase begins. During this phase, an increasing proportion of the block commit must be burnt. To burn this sunset fee, the miner must send the sunset fee amount to the first output of their block commit transaction (i.e., the OPRETURN output).

400,000 Bitcoin blocks after the sunset phase begins, the sunset phase ends. After this point, PoX is no longer active, and miners must burn all of their leader block commits. They do so by sending Bitcoin to the canonical burn address `1111111111111111111114oLvT2`.

**Comment by agraebe** [comment]
@kantai thanks, this is great!

@jasperjansz would you be able to help with illustrations for `Coinbase Rewards` and/or `Mining with Proof-of-Transfer`? Alternatively, we just add the content and mark the illustrations for later.

**Comment by jasperjansz** [comment]
@agraebe Here you go: https://www.figma.com/file/4XaD0Q2CBwuWCEkcMMAsfo/Docs?node-id=523%3A2292
