### ISSUE TITLE
DeFi content

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#825]
We should understand what high prioritiy defi-related content we should add to the docs. Here's a list to start with:

- [ ] Tutorial: Create your first coin
- [ ] An ERC20 definition (contract conventions) for the Stacks 2.0 network
- [ ] Guide to Stacks 2.0 tokens (fungible & NFT)
- [ ] Token sample contract
- [ ] Swapr sample UI
- [ ] Token generator UI

**Comment by agraebe** [comment]
@markmhx do you think you could get to this before mainnet?

**Comment by markmhx** [comment]
Yep I've been meaning to incorporate this into the Connect 2.0 documentation work generally per https://github.com/blockstack/docs/issues/926.
