### ISSUE TITLE
blockchain-api-client docs are not findable

### ISSUE THREAD

**Issue by dantrevino** [blockstack/docs#829]
This documentation went missing and I can't find it on the docs site anywhere. https://blockstack.github.io/stacks-blockchain-api/client/index.html

**Comment by psq** [comment]
is this what you are looking for https://blockstack.github.io/stacks-blockchain-api/ ?

**Comment by dantrevino** [comment]
Nope.  I'm looking for the js client library documentation.

**Comment by agraebe** [comment]
cc @zone117x as discussed in the docs channel. thanks for helping!

**Comment by zone117x** [comment]
Fixed this manually for now. In the long run we need to do https://github.com/blockstack/stacks-blockchain-api/issues/297
