### ISSUE TITLE
Problems with running a testnet node instructions

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs#833]
I was walking @maxlovescode through the initial [running a testnet node tutorial](https://github.com/blockstack/docs/blob/master/src/pages/stacks-blockchain/running-testnet-node.md) on Discord, and we discovered a step that might be tripping others up based on the output.

In Step 1: Installing the node, the instructions are as follows:

```
cargo build --workspace --bin stacks-node
# binary will be in target/debug/stacks-node
./target/debug/stacks-node krypton
# release build
cargo build --workspace --release --bin stacks-node
# binary will be in target/release/stacks-node
```

The second command actually *starts the follower node* so it begins to output data, and the user never gets to complete the third command. For those less familiar with the command-line, this feels like the installer "never completes".

What is the difference between the `--bin` and `--release` flag of cargo build in this case aside from the output location? My scripts all use `cargo testnet start` so I haven't tested out those commands.

We also ran into some issues with the PATH variable, where on his system (MacOS Catalina):
- running `stacks-node krypton` results in `command not found`, even if we are in the `./target/debug` folder
- running `./target/debug/stacks-node krypton` works (from stacks-blockchain folder)

This meant that Step 2 appeared to fail as well, and similar issues were seen in the mining tutorial that followed.

<img width="573" alt="Screen_Shot_2020-10-21_at_8 29 59_AM" src="https://user-images.githubusercontent.com/9038904/96732965-c73da100-136d-11eb-8ab9-8d39cb9cf5e7.png">

<img width="573" alt="Screen_Shot_2020-10-21_at_8 31 41_AM" src="https://user-images.githubusercontent.com/9038904/96732972-c9076480-136d-11eb-84d6-1be73a9e1d62.png">

**Comment by psq** [comment]
if you suggest running with `target/debug/stacks-node`, you don't need step 3.

the `--release` flag builds a non-debug binary, typically smaller, better optimized, but won't produce logs and errors as helpful to track down issue, so I would recommend only using debug mode during the testnet phase.

`stacks-node` won't work till you've run some form of `cargo install` or copied the executable yourself in the directory referenced by $PATH.  The alternative is to use the full path to the executable (will always work), or a relative path (something that does not start with`/`), but you need to run it from the correct location

**Comment by agnelvishal** [comment]
@psq So `target/debug/stacks-node` runs infinitely?
As per https://docs.blockstack.org/stacks-blockchain/running-testnet-node#running-a-miner after `./target/debug/stacks-node krypton` we have to run `cargo build --workspace --release --bin stacks-node`

**Comment by friedger** [comment]
Looks like this is fixed by https://github.com/blockstack/docs/pull/842
