### ISSUE TITLE
PoX algorithm overview

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#837]
A summary of the PoX algorithm that would help developers/miners/integrators understand the entire process

**Comment by joshmatix** [comment]
A short summary of the Proof of Transfer whitepaper, with links to the actual White Paper and a link to the White Paper reading.

Actual figures (as in current Source Code) related to the threshold for Stackers, Initial & Sunset phases, number of blocks per Reward Cycle, maximum BTC addresses per Reward Set etc..

A graphic illustrating the interaction between the various actors and components.

**Comment by agraebe** [comment]
This would be fantastic @joshmatix! Can you create a PR? Happy to help in any way possible. LMK

**Comment by joshmatix** [comment]
I created a PR. Is it ok?

**Comment by agraebe** [comment]
thanks @joshmatix - I'll take a look in a bit. I noticed the illustration wasn't included. maybe @jasperjansz could help as part of the upcoming docs week :)

**Comment by joshmatix** [comment]
Alex,

Being new to the github process, I wanted to make sure I was doing it
right, before adding more stuff.

Tom ..

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by joshmatix** [comment]
Added the graphic.
