### ISSUE TITLE
Naming update for Stacks rebrand 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/docs#841]
Change from … | Change to … | Type
-- | -- | --
Blockstack authentication | Stacks authentication | Name
Blockstack app | Stacks app | Name
Blockstack authenticator | Stacks authenticator | Name
Blockstack username | Stacks username | Name
Blockstack account | Stacks account | Name
“Blockstack provide both JavaScript and Ruby JWT libraries with support for this signing algorithm.” | “Stacks auth provide…” |  
“… using Blockstack Connect, a JavaScript library that makes it easy to integrate Blockstack into the UI of any web app. “ | “ … using Stacks Connect…”“ … integrate Stacks auth into the UI “ |

**Comment by GinaAbrams** [comment]
@agraebe received sign off from Muneeb on these [here](https://paper.dropbox.com/doc/Quick-Naming-Decision-on-the-Following--A~YJdPpE7skOMyh3GO~CeCacAg-rOJGscuJvYVh3aX7PwV0X)

Think any additional context needed?

**Comment by agraebe** [comment]
wonderful, thanks for confirming!

**Comment by friedger** [comment]
What about 
* Blockstack documentation
* Blockstack blockchain
* Blockstack network
* Blockstack overview
* Blockstack PBC
* Blockstack ID
* Blockstack data
* Blockstack Radiks
* Blockstack storage
* Blockstack Naming System
* Blockstack Smart contracting language
* Blockstack Owner Address
?

**Comment by agraebe** [comment]
@GinaAbrams could you help with decisions for the above?

also noting here - the preview image of the docs (twitter, discord, Linkedin, FB, etc) shows "Blockstack Docs". Should check if this can be changed as well

**Comment by GinaAbrams** [comment]
The general rule of thumb is that things can be changed to Stacks outside of BNS and storage due to conversations about these names. Quick answers here:

Blockstack documentation -> Stacks documentation 
Blockstack blockchain -> Stacks blockchain 
Blockstack network -> Stacks network 
Blockstack overview -> Stacks overview 
Blockstack ID -> Stacks ID 
Blockstack Naming System -> Blockchain naming system 
Blockstack Smart contracting language -> Stacks smart contract language (or simply Clarity) 
Blockstack owner address -> Stacks owner address
