### ISSUE TITLE
Add reference for clarity-js-sdk objects

### ISSUE THREAD

**Issue by friedger** [blockstack/docs#846]
The tutorial https://docs.blockstack.org/smart-contracts/testing-contracts has some information to start using the clarity-js-sdk. However, there is no link to further information.

In particular, 
* how to use `client.createQuery` with arguments like `buff` or `string-ascii`.
* how to add a new provider

**Comment by friedger** [comment]
Depends somehow on https://github.com/blockstack/docs/issues/732

What actions should be taken for the clarity-js-sdk documentation?

**Comment by agraebe** [comment]
True. I think the most future-proof thing to do here would be to generate something in JSON format. That could be displayed in any way/form inside the docs in the future. Do you think the lib could generate typedoc and output into a JSON format? I believe we wanted to research how solid of an option that would be

**Comment by friedger** [comment]
@agraebe a quick run of typedoc for @blockstack/clarity shows:
![Screenshot from 2020-11-05 23-04-38](https://user-images.githubusercontent.com/1449049/98301631-5deb9e00-1fbb-11eb-8050-fa8aa8082cd2.png)

Not too bad, needs more content :-)

**Comment by agraebe** [comment]
that's something! Is there a way this could be returned as JSON?

I think @yknl or @aulneau wanted to look into this a bit as well, so pinging as FYI

**Comment by friedger** [comment]
This PR of clarity-js-sdk contains a docs.json https://github.com/blockstack/clarity-js-sdk/pull/120

**Comment by friedger** [comment]
Using tsdocs-plugin-markdown generates md files that could be used directly

![Screenshot from 2020-11-06 16-17-27](https://user-images.githubusercontent.com/1449049/98391579-1d416280-2057-11eb-9a5d-b1778f2ab264.png)

**Comment by friedger** [comment]
There are the markdown files 
* for the package that contain only an index of modules -> one static route
* for modules that contain only an index of elements (interfaces, classes, enums) -> dynamic routes with static paths
* for all elements -> dynamic routes with static paths

![2020-11-07 13-30-05](https://user-images.githubusercontent.com/1449049/98441264-824f9380-20fd-11eb-84db-b77f98dd6ff3.gif)

This is the result so far re-using the generated md files.

Do you have any input how to make it look nice?

**Comment by friedger** [comment]
There was one issue with the typedoc-plugin-markdown about "Promise\<void>".

**Comment by friedger** [comment]
I have generalized the js lib reference. There is no clarity-js specific code anymore in the mentioned PR.

There are three parametrized files, the parameters are `lib` (identifier/key of the library), `type` (one of modules, classes, enums, interfaces), `file` (the the md file generated by typedocs).
The three files are:
* one index file for the library (global.md), 
* one index file for all modules, all interface, all enums, all classes
* one content file for each modules, interface, enum or class.

The current setup to add a new js lib reference is as follows:
1. add a library id/key, the data path to the typedoc files and the package name to `/src/_data/libs.json`
1. see the reference!

Missing pieces:
* add library reference to navigation
* add github actions for each js lib to import typedoc files
* fix links in md files (the link contains [lib]/[type] path)
* fix typedoc-plugin-markdown for content like Promise<void> or Promise<boolean>

**Comment by agraebe** [comment]
let's jam on this - I'd love to understand it better and see what we should do next
