### ISSUE TITLE
Replace social image for docs repo and website

### ISSUE THREAD

**Issue by friedger** [blockstack/docs#863]
When sharing a link to github issues in this repo the image contains the name "Blockstack". It should be "Stacks" according to #841 

**old**
![Screenshot from 2020-11-04 18-07-53](https://user-images.githubusercontent.com/1449049/98142915-bf7f1000-1ec8-11eb-9887-8cec608a5769.png)

**Comment by agraebe** [comment]
@jasperjansz could you help with this as well?

**Comment by agraebe** [comment]
This also needs to be fixed for the actual docs page preview. Currently, it looks like this:

<img width="470" alt="Screen Shot 2020-12-11 at 8 26 20 AM" src="https://user-images.githubusercontent.com/1671228/101928541-9702c980-3b8a-11eb-8a6f-0ecdd2507722.png">


@aulneau can you instruct where changes should be made? I can find the resources and make the changes

**Comment by agraebe** [comment]
fixed now.
