### ISSUE TITLE
Stacks.js/Blockstack.js/@stacks{auth,storage} detailed developer docs are missing

### ISSUE THREAD

**Issue by dantrevino** [blockstack/docs#875]
The detailed developer documentation that used to be available from the Github repo is now nowhere to be found.  Details of function return errors, callbacks, etc are critical to developers.

Currently the stacks.js docs point just to the generic docs.blockstack.org site.

**Comment by agraebe** [comment]
@yknl could you take a look and see what the solution might look like (updates/creation of tutorials, references, etc)?

**Comment by friedger** [comment]
Seems related to #732
