### ISSUE TITLE
New feature Request : Add a troubleshooting guide/list of useful commands in docs 

### ISSUE THREAD

**Issue by HariniRajan397** [blockstack/docs#881]
There are lots of discussions happening in Discord regarding troubleshooting testnet installation. It is better to capture common issues that happen during installation(such as rust missing / seed is not properly set for a miner) in a doc.  Even useful commands such as the one listed in the doc link can be added as a separate official doc. 

https://public.3.basecamp.com/p/5MqG1Vtpv16qPZ7XE7zCv4fM

This can help everyone. The example is given only with respect to the testnet doc as of now. But it's better to have such troubleshooting guide for all areas.

**Comment by HariniRajan397** [comment]
@agraebe Please have a look and if the basecamp doc looks good, I can add it as a separate section . We can ask community to help us add more details as well .  Thanks.

**Comment by agraebe** [comment]
it's a great doc! we likely need to update a variety of pages inside the docs - and potentially add a new section to the testnet page itself. I feel like I might be best suited to do this given my awareness of the content across all pages. Let me add this to my backlog.

How was this document created in the first place (by whom for what goals)?

**Comment by HariniRajan397** [comment]
Sounds good, Alex! The troubleshooting guide will be really very useful. I created the doc . I compiled the list of commands/points I felt is good to refer for my understanding ,  based on the discussions I followed on Discord.

**Comment by HariniRajan397** [comment]
It is even good to have a best practices guide along with troubleshooting , especially for Clarity (list of some known good practices) will be really helpful for the newcomers.
