### ISSUE TITLE
Update todo list tutorial screenshots with accurate URL for authenticator

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#911]
Right now they show datavault.org but should show app.blockstack.org

<img width="202" alt="Screen Shot 2020-11-12 at 17 42 19" src="https://user-images.githubusercontent.com/28991/99074350-dfdd5780-25b7-11eb-8c52-79d9d6aed633.png">

**Comment by agraebe** [comment]
who could we assign for that? will this be part of the connect 2.0 docs issue?

**Comment by markmhx** [comment]
Yep good idea, I've linked it to the issue for updating documentation Connect 2.0 generally: https://github.com/blockstack/docs/issues/926
