### ISSUE TITLE
Display shift after using TOC menu

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs#924]
I was reviewing the testnet node instructions today and after clicking on a menu item under "On this page", the content was squished in the center and a vertical scroll bar shows on the left nav.

Before and after picture below:

![20201120_002_Selection](https://user-images.githubusercontent.com/9038904/99830543-14529580-2b1b-11eb-91f3-71b97aeab121.png)

![20201120_003_Selection](https://user-images.githubusercontent.com/9038904/99830556-174d8600-2b1b-11eb-96b2-cbec303ee105.png)

**Comment by agraebe** [comment]
@aulneau could you take a look at some point? if you have instructions so others can help with a PR, please add. thanks!

**Comment by agraebe** [comment]
closing in favor of https://github.com/blockstack/docs/issues/924
