### ISSUE TITLE
Fix content formatting when navigating between pages

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#933]
Content formatting appears to get out of whack generally when I navigate between, with image assets substituting improperly and elements jumping around the screen. 

I assume it has something to do with how state is handled client-side, perhaps in relation to page-specific styles? I haven't noticed a specific pattern to the behavior.

Examples:

<img width="1250" alt="Screen Shot 2020-11-27 at 15 29 05" src="https://user-images.githubusercontent.com/28991/100609043-a887de00-330d-11eb-93b8-8823628c1820.png">
<img width="1210" alt="Screen Shot 2020-11-27 at 15 28 58" src="https://user-images.githubusercontent.com/28991/100609047-a9b90b00-330d-11eb-95c7-17d1dd161d15.png">
<img width="1095" alt="Screen Shot 2020-11-27 at 15 28 52" src="https://user-images.githubusercontent.com/28991/100609048-a9b90b00-330d-11eb-8c6b-3fd6acef321d.png">

**Comment by agraebe** [comment]
@aulneau was this fixed?
