### ISSUE TITLE
Broken link "for current token holders'

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs#942]
This page: Note: If you are a token holder and would like to review your unlocking schedule, visit the For current token holders page in this documentation.

The link in the note 404s

**Note**: If you are a token holder and would like to review your unlocking schedule, visit the **For current token holders** page in this documentation.

**Comment by agraebe** [comment]
We seem to miss a redirect. The old URL linked to is: https://docs.blockstack.org/org/tokenholders.

This happened after we changed user-facing wallet docs. This should now go to: https://docs.blockstack.org/references/faqs/stacks-token
