### ISSUE TITLE
Missing documentation about how to use string-utf8

### ISSUE THREAD

**Issue by friedger** [blockstack/docs#944]
There should be an example how to create a `string-utf8` object in Clarity.

For unsigned integers, you use prefix `u` like `u42`, and for `string-utf8` as well: `u"A wolf face 🐺"` and `(contact u"abc" string-var)` and `u"\u{1F384}"`

**Comment by agraebe** [comment]
did you see the recent merge that added this content: https://docs.blockstack.org/write-smart-contracts/values ?

If so, what's the delta you're looking for?

**Comment by friedger** [comment]
That is more for Web developer. I was looking for details for Clarity devs, like https://stackoverflow.com/questions/65186078/how-to-join-two-utf8-strings-together-in-clarity/65186079#65186079

**Comment by agraebe** [comment]
Ah, so it sounds like you would want to have better examples for the types, not the JS clarity values. Maybe this page is best for that: https://docs.blockstack.org/references/language-types ?

**Comment by alexkeating** [comment]
Took an attempt at adding this to language types
