### ISSUE TITLE
Broken Links on Testnet Page

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs#949]
On the [Stacks 2.0 Testnet](https://www.blockstack.org/testnet) page there are a two broken links.

Try Mining
- current link: https://docs.blockstack.org/mining
- should be: https://docs.blockstack.org/start-mining

Try Stacking
- current link: https://docs.blockstack.org/stacks-blockchain/integrate-stacking
- should be: https://docs.blockstack.org/understand-stacks/integrate-stacking

Also, I noticed some of the links don't open in a new window/tab, probably because they are on the same domain? Should they for consistency?
- [Try the Stacks Wallet](https://www.blockstack.org/p/stacks-wallet)
- [Earn bug bounties](https://www.blockstack.org/testnet/bounties#Bugs)
- [Build tools](https://www.blockstack.org/bounties#Tools)

**Comment by agraebe** [comment]
Missing redirects from the last PR changing up the folder structure

**Comment by agraebe** [comment]
cc @CharlieC3

**Comment by CharlieC3** [comment]
@agraebe Not sure I have the access to fix this, since this page is managed in webflow. I think @markmhx may be needed here, correct me if I'm wrong.

**Comment by aulneau** [comment]
@CharlieC3 generally when any route is changed in the doc, we need to add / update here https://github.com/blockstack/docs/blob/master/next.config.js#L9
