### ISSUE TITLE
Incorrect Links on Bug Bounty Page

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs#950]
I found one and it made me dig for a few more on the [Bug bounties](https://www.blockstack.org/testnet/bounties) page. :upside_down_face: 

Under Community Bounties, the link to `#StacksPack`:
- current link: https://www.blockstack.org/testnet/bounties#https://twitter.com/search?q=%23StacksPack
- should be: https://twitter.com/search?q=%23StacksPack

Under Terms: Services in scope, some of the repo links need to be updated:

docs.blockstack: still resolves but points to old name
- current link: https://github.com/blockstack/docs.blockstack
- should be: https://github.com/blockstack/docs

cli-blockstack: points to older stacks 1 version, based on readme should be stacks.js
- current link: https://github.com/blockstack/cli-blockstack
- should be: https://github.com/blockstack/stacks.js/tree/master/packages/cli

stacks-transactions-js: was also moved to the same monorepo for stacks.js
- current link: https://github.com/blockstack/stacks-transactions-js
- should be: https://github.com/blockstack/stacks.js/tree/master/packages/transactions

bounties: could point to repo instead of the readme inside of it
- current link: https://github.com/blockstack/bounties/blob/master/README.md
- should be: https://github.com/blockstack/bounties

**Comment by alexkeating** [comment]
I made a pr for this, but I was unable to find the bounty links in this repo. I was able to the cli, transactions and docs links.
