### ISSUE TITLE
Explain how to read the v2/info data

### ISSUE THREAD

**Issue by friedger** [blockstack/docs#980]
The properties returned by `v2/info` endpoint should be explained in details. What do they mean, what if they are different..

**Comment by agraebe** [comment]
did you see the field descriptions on here: https://blockstack.github.io/stacks-blockchain-api/#operation/get_core_api_info ?

what specific would be missing: something _inside_ the docs (as opposed on the reference page), or some clearly missing description details of the fields, or something else?

**Comment by agraebe** [comment]
going to closing this for now. please re-open with more details :)
