### ISSUE TITLE
Ecosystem / community content inside the docs

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#987]
During the docs sync, we talked about how fantastic http://stackstools.tilda.ws/ is. @jdbender66 created this in order to help developers get a glance on everything that might be relevant during the onboarding. There's a ton of great stuff in there and the delta to what is in the docs seems to be related to community and ecosystem tools/content/videos/etc.

The question is: How should we deal with this type of content? Could we create a new section? Could we better encourage community content to be added to existing content?

One simple idea might be to add a section to the docs homepage (http://docs.blockstack.org/), linking out to the tilda page

**Comment by jeffdomke** [comment]
Is the benefit: 

- Community/non docs resources? 
- Everything on a single page? 
- Organized by topic? 

Could be all but trying to get to the heart of it.

**Comment by agraebe** [comment]
Probably all of them, with the main being coverage of community resources

**Comment by pgray-hiro** [comment]
I'd love to talk more about this issue in our next sync, TBH a ton of the links on the Tilda page go right back into the official documentation.  We could either link to Tilda, or just establish our own External Resources page and take the links that he has gathered to other places.  I wouldn't be opposed to reaching out to Joe and seeing if he might want to become a more active contributor to the official documentation.

**Comment by jdbender66** [comment]
Yeah Stacks.Tools was definitely more relevant during the testnet. Was meant to be more of a list of links for developers to quickly access. Super down to revisit how we present our resources, and definitely willing to be more active in the docs.

**Comment by pgray-hiro** [comment]
I wonder if we just put an "Awesome Stacks" section in the docs and add all the community links.  In general I'd like to improve how the documentation feeds people into the community.

**Comment by agraebe** [comment]
Yeah, I really like the "Awesome X" framing. In fact, one of our community members (@friedger) created this a while back: https://github.com/friedger/awesome-blockstack

**Comment by pgray-hiro** [comment]
Do you think Friedger would be upset if we stole his idea?

**Comment by agraebe** [comment]
@friedger ... would you? ;) 

We could also just link out to the GH project from the docs and create a PR to update his readme

**Comment by pgray-hiro** [comment]
I'm happy to link to him from the main docs and contribute directly to his page as well

**Comment by friedger** [comment]
@agraebe I won't be upset.

Lots of projects to upgrade to stacks.. @pgray-hiro Let's update it!
