### ISSUE TITLE
Add guidance for implementing robust transaction handling in wallets

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#988]
Given recent issues with the testnet faucet, @hstove and I were thinking that it'd be worth writing up some standard guidance for how wallets should implement transactions in a robust way to avoid common issues due to congestion and other network difficulties that may require, for example, reattempted broadcasts and the like.

cc @kantai @agraebe @yknl @zone117x @kyranjamie in case you all have ideas about what kinds of information this guidance could or should contain.

**Comment by agraebe** [comment]
I'd suggest adding the some of the content (at least) to these pages:
- https://docs.blockstack.org/understand-stacks/transactions
- https://docs.blockstack.org/understand-stacks/sending-tokens

**Comment by agraebe** [comment]
should this be closed for now @markmhx ?

**Comment by markmhx** [comment]
I'm happy to keep it in our icebox for now, but we can also close if you think it's stale.

**Comment by agraebe** [comment]
we should add a stale bot to this repo. IMHO, if there's no "trigger" for icebox items to be prioritized, we might as well close it and reopen once it beomces more relevant.

**Comment by markmhx** [comment]
@yknl is this an active concern for you by chance? If not, we should probably close out until a wallet provider like yourself needs this sort of guidance.

**Comment by agraebe** [comment]
please reopen if it is a concern. thanks!
