### ISSUE TITLE
Link to @stacks/wallet-sdk README for address derivation guidance

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs#989]
We should capture [our decisions about address derivation](https://paper.dropbox.com/doc/Deriving-identities-while-retaining-the-same-STX-Address-across-products--BB3yzKd14KYc1V93ybPGKy6gAg-SSJX1wgXTV9ItlkWpPvat) in regards to existing and future usernames in a public-facing document that makes them clear to all 3rd party wallet developers for implementation.

Perhaps worth bundling with https://github.com/blockstack/docs/issues/988.

**Comment by markmhx** [comment]
@yknl interested in perhaps taking this one?

**Comment by friedger** [comment]
What should go into that guide?
* How can I transfer my username from stacks 1.0? 
    * get private key from old identity
    * send transfer to new address

I failed to get the right private key, I tried:
``` 
  const rootNode = await deriveRootKeychainFromMnemonic(seedPhrase);
  const child = rootNode.deriveHardened(888).deriveHardened(0).derive(1)
  const key = child.privateKey?.toString("hex") || ""
  let stxAddress= getAddressFromPrivateKey(key, TransactionVersion.Testnet);
  console.log(key, stxAddress)
``` 
But that address is not the address that currently owns my name. I am looking at fmdroid.id owned by `ST32E5EAFYTPG0PRZ5JJGHGCNREH8W9HGK7GRNWT5` according to bns.clar. The name was owned by the second identity ( `m/888'/0'/1'`)

**Comment by hstove** [comment]
FYI I've added this to the README for `@stacks/wallet-sdk`: https://github.com/blockstack/stacks.js/blob/feat/wallet-sdk/packages/wallet-sdk/README.md#generating-new-accounts - you want the 'data private key'.

This code should help with compatibility with `@stacks/transactions`:

```ts
const rootNode = await deriveRootKeychainFromMnemonic(seedPhrase);
const child = rootNode.deriveHardened(888).deriveHardened(0).deriveHardened(1)
const ecPair = ECPair.fromPrivateKey(child.privateKey);
const stxPrivateKey = ecPairToHexString(ecPair);
```

**Comment by markmhx** [comment]
We should link to this "wallet-sdk" README from the "Build apps" section navigation for discoverability:

![image](https://user-images.githubusercontent.com/28991/107642005-995dce80-6c74-11eb-92ef-1a36cb04248b.png)

**Comment by agraebe** [comment]
who could take this?
