### ISSUE TITLE
Testnet fees update suggestion

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#993]
[![Screenshot_2020-12-28_21-44-38.png](https://mrkr.io/s/5fea51c6cb32d33b88908c71/2)](https://mrkr.io/s/5fea51c6cb32d33b88908c71/0)

I'm using 1 and getting an error. The CLI is asking for 180. I'm assuming this can change again so maybe some general guidance opposed to a number. 

---

**Source URL:** [https://docs.blockstack.org/understand-stacks/command-line-interface](https://docs.blockstack.org/understand-stacks/command-line-interface)

<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.88</td></tr><tr><td><strong>Screen Size</strong></td><td>3360 x 1890</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1760 x 1322</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by agraebe** [comment]
@yknl could you suggest the change we need to make here? thanks!

**Comment by yknl** [comment]
This needs to be updated to at least 180. The example command below it has the fee at 200.

**Comment by agraebe** [comment]
could you please fix this in a quick PR @yknl ? 🙏🏼
