### ISSUE TITLE
Can't curl to the faucet in CLI

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#996]
[![Screenshot_2020-12-29_23-06-46.png](https://mrkr.io/s/5febb6861d5e8c7f3037df7c/2)](https://mrkr.io/s/5febb6861d5e8c7f3037df7c/0)

Response I get: "no matches found: https://stacks-node-api.xenon.blockstack.org/extended/v1/faucets/stx?address=ST1P3HXR80TKT48TKM2VTKCDBS4ET9396W0W2S3K8" 

Tried a handful of things to get around it. Removed `xenon` and tried swapping in the post I can successfully use on the faucet webpage and still can't get it to work. 

---

**Source URL:** [https://docs.blockstack.org/understand-stacks/stacking-using-CLI](https://docs.blockstack.org/understand-stacks/stacking-using-CLI)

<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.88</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1526 x 879</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by diwakergupta** [comment]
@jeffdomke what's the exact command you used? This works for me:

```bash
$ curl -X POST "https://stacks-node-api.xenon.blockstack.org/extended/v1/faucets/stx?address=ST1P3HXR80
TKT48TKM2VTKCDBS4ET9396W0W2S3K8"
{"success":true,"txId":"0xd3ef7ce64a009f1d73a52af35446c3785116e10f7770926d3469b2499ac1b741","txRaw":"80800000000400164247d6f2b425ac5771423ae6c80c754f7172b0000000000000011000000000000000b40000bd7d4d9116fdf25e49085ec3d206d1c546bd24a90598209d7f438c196698dd0313dced28f31e8e25a0643b921889fade801ef58b5b24ede8e4263a43108153bc03020000000000051a6c38f70806a7a22353a0b7a9b1abc91da48d26e0000000001dcd650046617563657400000000000000000000000000000000000000000000000000000000"}
```

**Comment by agraebe** [comment]
I used this command for faucet calls yesterday too. Can you try again to see if it reproduces on your end @jeffdomke ?

**Comment by jeffdomke** [comment]
Just rechecked and it works. Not sure what the deal was before. Closing.
