### ISSUE TITLE
RPC API broken link

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/docs#997]
[![Screenshot_2020-12-29_23-36-44.png](https://mrkr.io/s/5febbd8c3ae3147ed854fb57/2)](https://mrkr.io/s/5febbd8c3ae3147ed854fb57/0)

Looks like this is pointing to a reference that isn't there. Should this be pointing to the Stacks Blockchain API page subhead PRC? 

---

**Source URL:** [https://docs.blockstack.org/understand-stacks/running-testnet-node](https://docs.blockstack.org/understand-stacks/running-testnet-node)

<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.88</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1338 x 1265</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by agraebe** [comment]
Good catch, it should point to: https://docs.blockstack.org/understand-stacks/stacks-blockchain-api#stacks-node-rpc-api

meta: time to run the link checker again. it doesn't run automatically
